Machine Learning kya hai?
Model kya hai?
Training kya hai?
Prediction kya hai?
Feature kya hai?
Target kya hai?

In [ ]:
Experience              Salary
1                           10000
2                           20000
3                           30000
4                           40000

SyntaxError: invalid syntax (1645887967.py, line 1)

In [ ]:
# Algorithems
Liner Regration

logistic Regration

In [5]:
import pandas as pd
df=pd.DataFrame({
    "Experience":[1,2,3,4,5],
    "Salary":[20000,30000,40000,50000,60000]
})
X=df[['Experience']]
y=df[["Salary"]]
# Model Training
from sklearn.linear_model import LinearRegression 
model=LinearRegression()
model.fit(X,y)
model.predict([[10]])

c:\Users\Vishnu\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[110000.]])

In [ ]:
import pandas as pd
df=pd.DataFrame({
    "Experience":[1,2,3,4,5],
    "Salary":[20000,30000,40000,50000,60000]
})
X=df[['Experience']]
y=df[["Salary"]]
# Model Training
from sklearn.linear_model import LinearRegression 
model=LinearRegression()
model.fit(X,y) # Learning
model.predict([[10]])  # Prediction

In [6]:
df

   Experience  Salary
0           1   20000
1           2   30000
2           3   40000
3           4   50000
4           5   60000

In [13]:
df=pd.read_csv(r"C:\Users\Vishnu\Desktop\Python_Evening\archive\tested.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [15]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
# Loading  Data
df=pd.read_csv(r"C:\Users\Vishnu\Desktop\Python_Evening\archive\tested.csv")
# Missing Value Handling
df['Age']=df['Age'].fillna(df['Age'].median())
df['Cabin']=df['Cabin'].fillna(df['Cabin'].mode()[0])
df['Fare']=df['Fare'].fillna(df['Fare'].median())

# Encoding
df['Sex']=df['Sex'].map(
    {
        'male':0,
        'female':1
    }
)

# Feature Engineering
df['familysize']=(df['SibSp']+df['Parch']+1)

df['isAlone']=(df['familysize']==1).astype(int)


# Find Features

X=df[['Pclass','Sex','Age','Fare','familysize','isAlone']]
y=df['Survived']


X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

#Scalling
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)


# Model Training
model=LogisticRegression()
model.fit(X_train,y_train)

# prediction
y_pred=model.predict(X_test)

# Accuracy
accuracy=accuracy_score(y_test,y_pred)

print("Accuracy:",accuracy)

Accuracy: 1.0

In [ ]:
Actual Value                    Predicted

1                                   1
0                                   0
1                                   0
0                                   1
1                                   1
1                                   1

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 72  15]
 [ 13 100]]
              precision    recall  f1-score   support

           0       0.85      0.83      0.84        87
           1       0.87      0.88      0.88       113

    accuracy                           0.86       200
   macro avg       0.86      0.86      0.86       200
weighted avg       0.86      0.86      0.86       200

In [ ]:
Actual Value(Predicted)    0(Not Survived)                1(Survived)        
0                          50                                 0
1                          0                                 34

In [ ]:
84/84

In [21]:
# jamsedpur  100 criminals

# police operation
# police ---humne 50 criminals pakad liye

# 45 --criminals
# 5 innocent


pricision=45/50*100
print(pricision)

90.0

In [22]:
# jamsedpur  100 criminals

# police operation

# 45 --criminals

recall=45/100*100
print(recall)

45.0

In [23]:
# police  150
# criminals 100%
# innocent 50

recall=100/150*100
print(recall)

66.66666666666666

In [ ]:
ek model 
precision 100%
Recall 10%

Dusra Model
precision 50%
recall 100%

In [88]:
import pandas as pd
df = pd.read_csv("heart_disease.csv")
df

                                                                  import pandas as pd
def get_valid_input(message                        min_value              max_value):
    while True:                                    NaN                            NaN
        try:                                       NaN                            NaN
            value = int(input(message))            NaN                            NaN
            if min_value <= value <= max_value:    NaN                            NaN
                return value                       NaN                            NaN
            print(f"Please enter a value betwee... NaN                            NaN
        except ValueError:                         NaN                            NaN
            print("Invalid Input! Numbers Only")   NaN                            NaN
def predict_disease():                             NaN                            NaN
    print("\n===== Heart Disease Prediction Sys... NaN                            NaN
    age = get_valid_input(                         NaN                            NaN
        "Enter Age (1-120): "                      NaN                            NaN
        1                                          NaN                            NaN
        120                                        NaN                            NaN
    )                                              NaN                            NaN
    sex = get_valid_input(                         NaN                            NaN
        "Enter Gender (0 = Male                    1 = Female): "                 NaN
        0                                          NaN                            NaN
        1                                          NaN                            NaN
    )                                              NaN                            NaN
    chest_pain = get_valid_input(                  NaN                            NaN
        "Enter Chest Pain Type (0-3): "            NaN                            NaN
        0                                          NaN                            NaN
        3                                          NaN                            NaN
    )                                              NaN                            NaN
    blood_pressure = get_valid_input(              NaN                            NaN
        "Enter Blood Pressure (80-250): "          NaN                            NaN
        80                                         NaN                            NaN
        250                                        NaN                            NaN
    )                                              NaN                            NaN
    cholesterol = get_valid_input(                 NaN                            NaN
        "Enter Cholesterol (100-500): "            NaN                            NaN
        100                                        NaN                            NaN
        500                                        NaN                            NaN
    )                                              NaN                            NaN
    max_hr = get_valid_input(                      NaN                            NaN
        "Enter Max Heart Rate (60-250): "          NaN                            NaN
        60                                         NaN                            NaN
        250                                        NaN                            NaN
    )                                              NaN                            NaN
    new_data = pd.DataFrame({                      NaN                            NaN
        "Age": [age]                               NaN                            NaN
        "Sex": [sex]                               NaN                            NaN
        "ChestPain": [chest_pain]                  NaN                            NaN
        "BloodPressure": [blood_pressure]          NaN                            NaN
        "Cholesterol": [cholesterol]               NaN                            NaN
        "MaxHeartRate": [max_hr]                   NaN                            NaN
    })                                             NaN                            NaN
    prediction = model.predict(new_data)[0]        NaN                            NaN
    probability = model.predict_proba(new_data)[0] NaN                            NaN
    print("\n===== Prediction Result =====")       NaN                            NaN
    print(f"Disease Probability : {probability[... NaN                            NaN
    print(f"No Disease Probability : {probabili... NaN                            NaN
    if prediction == 1:                            NaN                            NaN
        print("\nHeart Disease Detected")          NaN                            NaN
    else:                                          NaN                            NaN
        print("\nNo Heart Disease Detected")       NaN                            NaN
# Function Call                                    NaN                            NaN
predict_disease()                                  NaN                            NaN

In [56]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

df = pd.read_csv("heart_disease.csv")

X = df.drop("Disease", axis=1)
y = df["Disease"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.4,
    random_state=42
)

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)
print("Model Trained Successfully")

KeyError: "['Disease'] not found in axis"

In [57]:
X_train

     Age  Sex  ChestPain  BloodPressure  Cholesterol  MaxHeartRate
249   49    0          2            113          332           198
433   35    0          0            141          355           149
19    73    0          0            161          290           162
322   50    0          1            114          248           181
332   51    1          0            138          227           159
..   ...  ...        ...            ...          ...           ...
106   40    0          1            108          377           110
270   60    0          3            139          331           133
348   62    0          1            153          366           155
435   72    0          2            126          383           121
102   30    1          0            119          166           135

[400 rows x 6 columns]

In [58]:
X_test

     Age  Sex  ChestPain  BloodPressure  Cholesterol  MaxHeartRate
361   35    1          2            108          154           157
73    63    1          1            136          209           167
374   52    0          3            172          267           138
155   33    1          1            144          235           131
104   37    1          2            136          385           132
..   ...  ...        ...            ...          ...           ...
347   76    0          0            162          380           198
86    74    0          2            118          280           182
75    65    1          1            184          366           155
438   37    0          1            106          391           102
15    32    1          0            186          178           155

[100 rows x 6 columns]

In [59]:
y_train

249    0
433    0
19     1
322    0
332    0
      ..
106    0
270    1
348    1
435    1
102    0
Name: Disease, Length: 400, dtype: int64

In [60]:
y_test

361    0
73     0
374    1
155    0
104    1
      ..
347    1
86     1
75     1
438    0
15     0
Name: Disease, Length: 100, dtype: int64

In [61]:
y_pred=model.predict(X_test)

In [62]:
from  sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test,y_pred))

[[39 10]
 [ 4 47]]

In [63]:
TN       FP
FN       TP

SyntaxError: invalid syntax (1590104575.py, line 1)

In [64]:
for i in y_pred:
    print(i)

0
0
1
0
1
1
0
0
0
1
1
0
1
1
0
1
0
0
1
1
0
0
0
1
0
0
1
1
1
1
0
1
0
0
1
0
1
1
0
1
1
1
0
0
0
1
0
0
1
0
1
1
1
0
1
1
0
1
0
1
1
0
0
1
0
0
1
1
0
0
0
1
1
1
1
1
1
1
1
0
0
1
1
1
1
1
0
0
1
1
0
0
1
1
1
1
1
1
1
0

In [65]:
y_test

361    0
73     0
374    1
155    0
104    1
      ..
347    1
86     1
75     1
438    0
15     0
Name: Disease, Length: 100, dtype: int64

In [66]:
Acutal Value                Predicted_Value              Result
1                           0                            FN
1                           0                            FN
1                           0                            FN
1                           1                            TP
1                           1                            TP
0                           0                            TN
1                           0                            FN
1                           1                            TP

SyntaxError: invalid syntax (1520381079.py, line 1)

In [67]:
FN=4
TP=3
TN=1
FP=0

              PREDICTED VALUE
ACUTAL         0            1
    0          TN(1)        FP(0)
    1          FN(4)        TP(3)

In [68]:
Accuracy=(TP+TN)/8
print("Accuracy:-",Accuracy)

Accuracy:- 0.5

In [69]:
# precision=TP/predictedyes
precision=3/3
print(precision)

1.0

In [70]:
# recall=TP/actual yes
recall=TP/7
print("recall:-",recall)

recall:- 0.42857142857142855

In [71]:
total=precision+recall
combine=recall*precision

In [72]:
[1,2,3,4,5]
F1_SCORE=2*combine/total
print(F1_SCORE)

0.6

In [73]:
from sklearn.metrics import *

print("Accuracy :", accuracy_score(y_test,y_pred))
print("Precision :", precision_score(y_test,y_pred))
print("Recall :", recall_score(y_test,y_pred))
print("F1 Score :", f1_score(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

Accuracy : 0.86
Precision : 0.8245614035087719
Recall : 0.9215686274509803
F1 Score : 0.8703703703703703
[[39 10]
 [ 4 47]]

In [74]:
error_rate=1-Accuracy

In [75]:
print(error_rate)

0.5

In [76]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))
from sklearn.metrics import *

print("Accuracy :", accuracy_score(y_test,y_pred))
print("Precision :", precision_score(y_test,y_pred))
print("Recall :", recall_score(y_test,y_pred))
print("F1 Score :", f1_score(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.80      0.85        49
           1       0.82      0.92      0.87        51

    accuracy                           0.86       100
   macro avg       0.87      0.86      0.86       100
weighted avg       0.86      0.86      0.86       100

Accuracy : 0.86
Precision : 0.8245614035087719
Recall : 0.9215686274509803
F1 Score : 0.8703703703703703
[[39 10]
 [ 4 47]]

In [77]:
df

                                                                  import pandas as pd
def get_valid_input(message                        min_value              max_value):
    while True:                                    NaN                            NaN
        try:                                       NaN                            NaN
            value = int(input(message))            NaN                            NaN
            if min_value <= value <= max_value:    NaN                            NaN
                return value                       NaN                            NaN
            print(f"Please enter a value betwee... NaN                            NaN
        except ValueError:                         NaN                            NaN
            print("Invalid Input! Numbers Only")   NaN                            NaN
def predict_disease():                             NaN                            NaN
    print("\n===== Heart Disease Prediction Sys... NaN                            NaN
    age = get_valid_input(                         NaN                            NaN
        "Enter Age (1-120): "                      NaN                            NaN
        1                                          NaN                            NaN
        120                                        NaN                            NaN
    )                                              NaN                            NaN
    sex = get_valid_input(                         NaN                            NaN
        "Enter Gender (0 = Male                    1 = Female): "                 NaN
        0                                          NaN                            NaN
        1                                          NaN                            NaN
    )                                              NaN                            NaN
    chest_pain = get_valid_input(                  NaN                            NaN
        "Enter Chest Pain Type (0-3): "            NaN                            NaN
        0                                          NaN                            NaN
        3                                          NaN                            NaN
    )                                              NaN                            NaN
    blood_pressure = get_valid_input(              NaN                            NaN
        "Enter Blood Pressure (80-250): "          NaN                            NaN
        80                                         NaN                            NaN
        250                                        NaN                            NaN
    )                                              NaN                            NaN
    cholesterol = get_valid_input(                 NaN                            NaN
        "Enter Cholesterol (100-500): "            NaN                            NaN
        100                                        NaN                            NaN
        500                                        NaN                            NaN
    )                                              NaN                            NaN
    max_hr = get_valid_input(                      NaN                            NaN
        "Enter Max Heart Rate (60-250): "          NaN                            NaN
        60                                         NaN                            NaN
        250                                        NaN                            NaN
    )                                              NaN                            NaN
    new_data = pd.DataFrame({                      NaN                            NaN
        "Age": [age]                               NaN                            NaN
        "Sex": [sex]                               NaN                            NaN
        "ChestPain": [chest_pain]                  NaN                            NaN
        "BloodPressure": [blood_pressure]          NaN                            NaN
        "Cholesterol": [cholesterol]               NaN                            NaN
        "MaxHeartRate": [max_hr]                   NaN                            NaN
    })                                             NaN                            NaN
    prediction = model.predict(new_data)[0]        NaN                            NaN
    probability = model.predict_proba(new_data)[0] NaN                            NaN
    print("\n===== Prediction Result =====")       NaN                            NaN
    print(f"Disease Probability : {probability[... NaN                            NaN
    print(f"No Disease Probability : {probabili... NaN                            NaN
    if prediction == 1:                            NaN                            NaN
        print("\nHeart Disease Detected")          NaN                            NaN
    else:                                          NaN                            NaN
        print("\nNo Heart Disease Detected")       NaN                            NaN
# Function Call                                    NaN                            NaN
predict_disease()                                  NaN                            NaN

In [78]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)
model.fit(scaled_X_train, y_train)
print(scaled_X_train)

[[-0.4291123  -0.93228691  0.51625965 -1.22419719  0.86548753  1.74913116]
 [-1.42456752 -0.93228691 -1.2872675  -0.13714347  1.18690542  0.23593506]
 [ 1.27738235 -0.93228691 -1.2872675   0.63932347  0.27855052  0.63739525]
 ...
 [ 0.49523897 -0.93228691 -0.38550393  0.32873669  1.34062702  0.42122438]
 [ 1.20627841 -0.93228691  0.51625965 -0.71949368  1.57819676 -0.62874842]
 [-1.78008724  1.07263117 -1.2872675  -0.99125711 -1.45431113 -0.19640668]]

In [79]:
def predict_disease(Age,Sex,ChestPain,BloodPressure,Cholesterol,MaxHeartRate):
    data=[[
        Age,
        Sex,
        ChestPain,
        BloodPressure,
        Cholesterol,
        MaxHeartRate

    ]]

    prediction=model.predict(data)[0]
    if precision==1:
        return "Heart Disease Detected"
    else:
        return "No Disease Detected"
result=predict_disease(
    Age=int(input("Enter Your Age")),
    Sex=int(input("Enter Your Gender Male for ENTER 0 FEMALE FOR 1")),
    ChestPain=int(input("Chest Pin Value")),
    BloodPressure=int(input("Enter Your Blood Pressure")),
    Cholesterol=250,
    MaxHeartRate=140
)
print(result)

Heart Disease Detected

In [85]:
df.corr()

ValueError: could not convert string to float: ' max_value):'

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(10,5))
sns.heatmap(df.corr(numeric_only=True),annot=True,cmap='coolwarm',linewidths=0.5)
plt.show()

ValueError: zero-size array to reduction operation fmin which has no identity

In [ ]:
print(df['Disease'].value_counts())

Disease
1    14
0     6
Name: count, dtype: int64

In [ ]:
y_pred=model.predict(X_test)
print(y_test.values)
print(y_pred)

[1 1 1 1 1 0 1 1]
[1 1 1 1 1 1 1 1]

c:\Users\Vishnu\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(42)
rows=500

age=np.random.randint(30,80,rows)
sex=np.random.randint(0,2,rows)
chest_pain=np.ranom.randint(0,4,rows)
bp=np.random.randint(100,190,rows)
cholesterol=np.random.randint(150,400,rows)
max_hr=np.random.randint(90,200,rows)
disease=(
    (age>55).astype(int)
    

)

In [ ]:
# print(df["Disease"].value_counts())

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

df=pd.read_csv('heart_disease_500.csv')

X=df.drop('Disease',axis=1)
y=df['Disease']

X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model=LogisticRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

print("Model Trained Successfully")

Model Trained Successfully

In [98]:
from sklearn.metrics import *
print("Accuracy :", accuracy_score(y_test,y_pred))
print("Precision :", precision_score(y_test,y_pred))
print("Recall :", recall_score(y_test,y_pred))
print("F1 Score :", f1_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

Accuracy : 0.86
Precision : 0.8245614035087719
Recall : 0.9215686274509803
F1 Score : 0.8703703703703703
[[39 10]
 [ 4 47]]

In [105]:
def predict_disease(Age,Sex,ChestPain,BloodPressure,Cholesterol,MaxHeartRate):
    data=[[
        Age,
        Sex,
        ChestPain,
        BloodPressure,
        Cholesterol,
        MaxHeartRate

    ]]

    prediction=model.predict(data)[0]
    if prediction==1:
        return "Heart Disease Detected"
    else:
        return "No Disease Detected"
result=predict_disease(
    Age=int(input("Enter Your Age")),
    Sex=int(input("Enter Your Gender Male for ENTER 0 FEMALE FOR 1")),
    ChestPain=int(input("Chest Pin Value")),
    BloodPressure=int(input("Enter Your Blood Pressure")),
    Cholesterol=250,
    MaxHeartRate=140
)
print(result)

Heart Disease Detected

c:\Users\Vishnu\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [106]:
df

     Age  Sex  ChestPain  BloodPressure  Cholesterol  MaxHeartRate  Disease
0     68    1          1            127          178           135        0
1     58    0          3            184          288           157        1
2     44    0          3            148          182           122        1
3     72    1          3            170          283            90        1
4     37    0          3            180          260           108        1
..   ...  ...        ...            ...          ...           ...      ...
495   34    0          0            175          262           190        0
496   41    0          2            135          225           152        0
497   45    1          2            151          368           151        1
498   55    0          1            175          221           188        0
499   55    0          1            106          238            96        0

[500 rows x 7 columns]

In [107]:
import pandas as pd

def get_valid_input(message,min_value,max_value):
    while True:
        try:
            value=int(input(message))
            if min_value<=value<=max_value:
                return value
            print(f"Please Enter Valid Value  between {min_value} to {max_value}")
        except ValueError:
            print("Invalid Value Entered")
def predict_disease():
    age=get_valid_input(
        "Enter Age (1-120) ",
        1,
        120
    )
    sex=get_valid_input(
        "Enter Gender (0= Male,1=Female)",
        0,
        1
    )
    chest_pain=get_valid_input(
        "Enter Chest Pain Type(0-3)",
        0,
        3
    )
    blood_presure=get_valid_input(
        "Enter Blood Pressure (80-250)",
        80,
        250
    )
    cholesterol=get_valid_input(
        "Enter Cholesterol (100-500)",
        100,
        500
    )
    max_hr=get_valid_input(
        "Enter Max Heart Rate (60-250):",
        60,
        250
    )

    new_data=pd.DataFrame({
        'Age':[age],
        'Sex':[sex],
        'ChestPain':[chest_pain],
        'BloodPressure':[blood_presure],
        'Cholesterol':[cholesterol],
        'MaxHeartRate':[max_hr]  
    })
    prediction=model.predict(new_data)[0]
    probability=model.predict_proba(new_data)[0]
    

    print(f"Disease Probability:{probability[1]*100:.2f}%")
    print(f"No Disease Probability:{probability[0]*100:.2f}%")

    if prediction==1:
        print("Heart Disease Detected")
    else:
        print("No Disease Detected")

predict_disease()

Please Enter Valid Value  between 1 to 120
Please Enter Valid Value  between 1 to 120
Please Enter Valid Value  between 0 to 1
Please Enter Valid Value  between 0 to 3
Please Enter Valid Value  between 80 to 250
Please Enter Valid Value  between 80 to 250
Please Enter Valid Value  between 100 to 500
Please Enter Valid Value  between 100 to 500
Please Enter Valid Value  between 60 to 250
Please Enter Valid Value  between 60 to 250
Disease Probability:99.09%
No Disease Probability:0.91%
Heart Disease Detected

Skills?
    |
    |
    -----No
            --Not Selected
    ----Yes
            ----Project?
                    |
                    |---Yes
                            ---Selected
                    ----No
                        |
                        |--Not Selected

In [7]:
import requests

# ======================================
# CONFIGURATION
# ======================================

API_KEY = "4b325e39c8mshc7812fc033baf96p18d1d3jsnf286fc1ef2fe"

BASE_URL = "https://real-time-pnr-status-api-for-indian-railways.p.rapidapi.com"

HEADERS = {
    "x-rapidapi-key": API_KEY,
    "x-rapidapi-host": "real-time-pnr-status-api-for-indian-railways.p.rapidapi.com",
    "Content-Type": "application/json"
}


# ======================================
# PNR CHECK FUNCTION
# ======================================

def check_pnr(pnr):

    url = f"{BASE_URL}/name/{pnr}"

    try:

        response = requests.get(
            url,
            headers=HEADERS,
            timeout=20
        )

        if response.status_code != 200:
            print(f"\nHTTP Error : {response.status_code}")
            print(response.text)
            return

        data = response.json()

        print("\n" + "=" * 70)
        print("               INDIAN RAILWAYS PNR STATUS")
        print("=" * 70)

        print(f"PNR Number        : {data.get('pnrNo', 'N/A')}")
        print(f"Train Number      : {data.get('trainNum', 'N/A')}")
        print(f"Train Name        : {data.get('trainName', 'N/A')}")
        print(f"Journey Class     : {data.get('journeyClass', 'N/A')}")
        print(f"Departure         : {data.get('departureDate', 'N/A')}")
        print(f"Arrival           : {data.get('arrivalDate', 'N/A')}")
        print(f"From Station      : {data.get('stationFrom', 'N/A')}")
        print(f"To Station        : {data.get('stationTo', 'N/A')}")
        print(f"Boarding Point    : {data.get('boardingPoint', 'N/A')}")
        print(f"Reservation Upto  : {data.get('reservationUpTo', 'N/A')}")
        print(f"Passengers        : {data.get('noOfPassenger', 'N/A')}")
        print(f"Chart Status      : {data.get('chartStts', 'N/A')}")

        print("\n" + "=" * 70)
        print("Passenger Details")
        print("=" * 70)

        passengers = data.get("passengerDetailsDTO", [])

        if passengers:

            for p in passengers:

                print(f"\nPassenger #{p.get('serialNo')}")

                print("-" * 40)

                print(f"Name          : {p.get('displayName','N/A')}")
                print(f"Age           : {p.get('age','N/A')}")
                print(f"Gender        : {p.get('gender','N/A')}")
                print(f"Quota         : {p.get('quotaCode','N/A')}")
                print(f"Seat Status   : {p.get('seatStts','N/A')}")
                print(f"Coach         : {p.get('coachNo') or 'Not Assigned'}")
                print(f"Seat Number   : {p.get('seatNo') or 'Not Assigned'}")

        else:
            print("No Passenger Details Found.")

        if data.get("errorMsg"):
            print("\nError :", data["errorMsg"])

        print("\n" + "=" * 70)

    except Exception as e:
        print("Error :", e)


# ======================================
# MAIN
# ======================================

def main():

    print("=" * 70)
    print("        INDIAN RAILWAY PNR STATUS CHECKER")
    print("=" * 70)

    while True:

        pnr = input("\nEnter 10-digit PNR Number : ").strip()

        if not (pnr.isdigit() and len(pnr) == 10):
            print("Invalid PNR Number")
            continue

        check_pnr(pnr)

        again = input("\nCheck Another PNR? (y/n): ").lower()

        if again != "y":
            break

    print("\nThank You!")


if __name__ == "__main__":
    main()

======================================================================
        INDIAN RAILWAY PNR STATUS CHECKER
======================================================================

======================================================================
               INDIAN RAILWAYS PNR STATUS
======================================================================
PNR Number        : 2749628734
Train Number      : 20806
Train Name        : AP EXPRESS
Journey Class     : 2A
Departure         : 23-12-2023  22:05
Arrival           : 25-12-2023  04:10
From Station      : AGC
To Station        : VSKP
Boarding Point    : AGC
Reservation Upto  : VSKP
Passengers        : 4
Chart Status      : CHART PREPARED

======================================================================
Passenger Details
======================================================================

Passenger #1
----------------------------------------
Name          : M V x x xxxxx
Age           : 34
Gender        : M
Quota         : GN
Seat Status   : CNF
Coach         : Not Assigned
Seat Number   : Not Assigned

Passenger #2
----------------------------------------
Name          : B Axxxxx
Age           : 27
Gender        : F
Quota         : GN
Seat Status   : CNF
Coach         : Not Assigned
Seat Number   : Not Assigned

Passenger #3
----------------------------------------
Name          : N Gxxxxx
Age           : 33
Gender        : M
Quota         : GN
Seat Status   : CNF
Coach         : Not Assigned
Seat Number   : Not Assigned

Passenger #4
----------------------------------------
Name          : R Pxxxxx
Age           : 32
Gender        : F
Quota         : GN
Seat Status   : CNF
Coach         : Not Assigned
Seat Number   : Not Assigned

======================================================================

Thank You!

SyntaxError: invalid syntax (3528599804.py, line 1)