                                    Pandas for Machine Learning Roadmap
    Module 1: Pandas Fundamentals

    Introduction to Pandas
    Series
    DataFrame
    Creating DataFrame
    Reading CSV, Excel, JSON
    Writing CSV, Excel

    Module 2: Data Exploration
    head()
    tail()
    sample()
    shape
    columns
    index
    info()
    describe()
    dtypes

    Module 3: Data Selection
    Column Selection
    Multiple Column Selection
    Row Selection
    loc[]
    iloc[]

Module 4: Data Filtering
Conditional Filtering
Multiple Conditions (&, |)
isin()
between()
query()

Module 5: Data Cleaning (Most Important for ML)

Missing Values
isnull()
notnull()
fillna()
dropna()
Duplicate Records
duplicated()
drop_duplicates()

Module 6: Data Transformation
Add New Columns
Update Existing Columns
Rename Columns
Change Data Types
astype()
replace()
apply()
map()

Module 7: String Operations
str.upper()
str.lower()
str.strip()
str.contains()
str.split()
str.replace()

Module 8: Date & Time Handling
to_datetime()
Year Extraction
Month Extraction
Day Extraction
Weekday Extraction
Date Difference

Module 9: Sorting & Ranking
sort_values()
sort_index()
rank()
nlargest()
nsmallest()

Module 10: Aggregation & Statistics
sum()
mean()
median()
mode()
max()
min()
count()
std()
var()
corr()
Module 11: GroupBy (Very Important)
groupby()
Single Aggregation
Multiple Aggregations
Custom Aggregations
GroupBy + Filter
Module 12: Reshaping Data
Pivot Table
Crosstab
Melt
Stack
Unstack
Module 13: Combining Data
concat()
merge()
Inner Join
Left Join
Right Join
Outer Join
join()

Module 14: Feature Engineering for ML
Creating Features
Binning (cut)
Quantile Binning (qcut)
Encoding Categories
Dummy Variables (get_dummies)
Label Encoding Preparation

In [ ]:
pip install pandas

In [ ]:
import pandas as pd
# How to Create Series
series=pd.Series([1,2,3,4,5])

In [ ]:
print(series)

In [ ]:
print(type(series))

In [3]:
# DataFrame
# How to Create DataFrame
import pandas as pd
data={'Name':['Alice','Bob','Charlie'],'Age':[25,30,35],'City':['New York','Los Angeles','Chicago']}
print(type(data))
df=pd.DataFrame(data)
print(type(df))

<class 'dict'>
<class 'pandas.core.frame.DataFrame'>

In [4]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [5]:
df=pd.read_csv('data.csv')
print(df)

     Roll    Name  Class  Marks
1  Vishnu     MCA    450    NaN
2   Vinit  B.Tech    487    NaN

In [7]:
dict={'Name':'Alice','Age':25,'City':'New York'}
df=pd.Series(dict)
print(df)

Name       Alice
Age           25
City    New York
dtype: object

In [8]:
print(type(df))

<class 'pandas.core.series.Series'>

In [12]:
data=pd.read_excel(r"C:\Users\Vishnu\Desktop\Python_Evening\RL_Task_Scheduling_Dataset.xlsx")

In [13]:
data

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0          1            91               9         3            28
1          2            12               9         3            55
2          3            56              12         4            16
3          4            83              14         4            59
4          5            57              12         1            79
..       ...           ...             ...       ...           ...
295      296            56              15         4            24
296      297            80               9         3            96
297      298            25               3         3            72
298      299            85               7         2            96
299      300            19               8         2            65

[300 rows x 5 columns]

In [15]:
data.head()

   Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0        1            91               9         3            28
1        2            12               9         3            55
2        3            56              12         4            16
3        4            83              14         4            59
4        5            57              12         1            79

In [16]:
data.tail()

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
295      296            56              15         4            24
296      297            80               9         3            96
297      298            25               3         3            72
298      299            85               7         2            96
299      300            19               8         2            65

In [17]:
data.head(20)

    Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0         1            91               9         3            28
1         2            12               9         3            55
2         3            56              12         4            16
3         4            83              14         4            59
4         5            57              12         1            79
5         6            20              10         5            17
6         7            61               7         2            67
7         8            26              13         5            58
8         9            66               7         4            42
9        10            62               7         2            87
10       11            55               8         4            73
11       12            93              14         1            52
12       13            82              15         3            73
13       14            56               9         1            56
14       15            98              10         3             3
15       16            23               8         3            75
16       17            90               6         1            35
17       18            68               7         4            48
18       19            27               9         1            95
19       20            35               9         1            47

In [30]:
print(data[10:21])

    Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
10       11            55               8         4            73
11       12            93              14         1            52
12       13            82              15         3            73
13       14            56               9         1            56
14       15            98              10         3             3
15       16            23               8         3            75
16       17            90               6         1            35
17       18            68               7         4            48
18       19            27               9         1            95
19       20            35               9         1            47
20       21            91               3         2            31

In [32]:
print(data.iloc[10:21,0:4])

    Task_ID  Task_Size_MB  Execution_Time  Priority
10       11            55               8         4
11       12            93              14         1
12       13            82              15         3
13       14            56               9         1
14       15            98              10         3
15       16            23               8         3
16       17            90               6         1
17       18            68               7         4
18       19            27               9         1
19       20            35               9         1
20       21            91               3         2

In [34]:
data.shape

(300, 5)

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Task_ID         300 non-null    int64
 1   Task_Size_MB    300 non-null    int64
 2   Execution_Time  300 non-null    int64
 3   Priority        300 non-null    int64
 4   Arrival_Time    300 non-null    int64
dtypes: int64(5)
memory usage: 11.8 KB

In [36]:
data.isnull().sum()

Task_ID           0
Task_Size_MB      0
Execution_Time    0
Priority          0
Arrival_Time      0
dtype: int64

In [37]:
data.columns

Index(['Task_ID', 'Task_Size_MB', 'Execution_Time', 'Priority',
       'Arrival_Time'],
      dtype='object')

In [39]:
data['Task_Size_MB'].value_counts()

Task_Size_MB
37    9
95    8
56    7
33    7
20    6
     ..
39    1
36    1
84    1
87    1
41    1
Name: count, Length: 87, dtype: int64

In [40]:
data['Task_Size_MB'].unique()

array([ 91,  12,  56,  83,  57,  20,  61,  26,  66,  62,  55,  93,  82,
        98,  23,  90,  68,  27,  35,  94,  65,  40,  10,  46,  29,  22,
        34,  72,  59,  74,  95,  52,  97,  42,  33,  53,  79,  71,  32,
        11,  51,  18,  43,  50,  60,  85,  15,  21,  37,  13,  17,  14,
        76,  88,  38,  81,  80,  70,  19,  24,  48,  99,  77,  54,  58,
        47,  92,  44,  16,  64,  63,  75,  39,  89,  78,  25, 100,  49,
        69,  31,  30,  36,  67,  96,  84,  87,  41])

In [42]:
data.index

RangeIndex(start=0, stop=300, step=1)

In [43]:
data.describe()

          Task_ID  Task_Size_MB  Execution_Time    Priority  Arrival_Time
count  300.000000    300.000000      300.000000  300.000000    300.000000
mean   150.500000     55.170000        8.116667    3.036667     52.006667
std     86.746758     27.261052        4.060132    1.417281     29.338640
min      1.000000     10.000000        1.000000    1.000000      1.000000
25%     75.750000     33.000000        5.000000    2.000000     27.000000
50%    150.500000     55.000000        8.000000    3.000000     53.000000
75%    225.250000     80.000000       11.250000    4.000000     77.000000
max    300.000000    100.000000       15.000000    5.000000    100.000000

In [44]:
data['Task_Size_MB'].mean()

np.float64(55.17)

In [45]:
data['Arrival_Time']

0      28
1      55
2      16
3      59
4      79
       ..
295    24
296    96
297    72
298    96
299    65
Name: Arrival_Time, Length: 300, dtype: int64

In [46]:
data[['Task_Size_MB','Arrival_Time']]

     Task_Size_MB  Arrival_Time
0              91            28
1              12            55
2              56            16
3              83            59
4              57            79
..            ...           ...
295            56            24
296            80            96
297            25            72
298            85            96
299            19            65

[300 rows x 2 columns]

In [47]:
data.loc[0]

Task_ID            1
Task_Size_MB      91
Execution_Time     9
Priority           3
Arrival_Time      28
Name: 0, dtype: int64

In [48]:
data.iloc[0]

Task_ID            1
Task_Size_MB      91
Execution_Time     9
Priority           3
Arrival_Time      28
Name: 0, dtype: int64

In [57]:
data.loc[0,'Arrival_Time']

np.int64(28)

In [58]:
data.iloc[0,4]

np.int64(28)

In [51]:
data

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0          1            91               9         3            28
1          2            12               9         3            55
2          3            56              12         4            16
3          4            83              14         4            59
4          5            57              12         1            79
..       ...           ...             ...       ...           ...
295      296            56              15         4            24
296      297            80               9         3            96
297      298            25               3         3            72
298      299            85               7         2            96
299      300            19               8         2            65

[300 rows x 5 columns]

In [60]:
data.sample(5)

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
69        70            33              12         1            74
287      288            44               5         3            93
185      186            44               8         5            70
290      291            25               7         3            14
91        92            81               6         4             2

In [61]:
data1=data.copy()

In [62]:
data1

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0          1            91               9         3            28
1          2            12               9         3            55
2          3            56              12         4            16
3          4            83              14         4            59
4          5            57              12         1            79
..       ...           ...             ...       ...           ...
295      296            56              15         4            24
296      297            80               9         3            96
297      298            25               3         3            72
298      299            85               7         2            96
299      300            19               8         2            65

[300 rows x 5 columns]

In [63]:
print(type(data1))

<class 'pandas.core.frame.DataFrame'>

In [64]:
print(data.loc[[295]])

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
295      296            56              15         4            24

In [ ]:
Module 4: Data Filtering
Conditional Filtering
Multiple Conditions (&, |)
isin()
between()
query()

In [65]:
data

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0          1            91               9         3            28
1          2            12               9         3            55
2          3            56              12         4            16
3          4            83              14         4            59
4          5            57              12         1            79
..       ...           ...             ...       ...           ...
295      296            56              15         4            24
296      297            80               9         3            96
297      298            25               3         3            72
298      299            85               7         2            96
299      300            19               8         2            65

[300 rows x 5 columns]

In [ ]:
Module 4: Data Filtering
Conditional Filtering
Multiple Conditions (&, |)
isin()
between()
query()

In [66]:
import pandas as pd

data=pd.DataFrame(

    {
        "Name":['Alice','Bob','Charlie','David','Eve'],
        "Age":[25,30,35,40,45],
        "City":['New York','Los Angeles','Chicago','Houston','Phoenix'],
        "Salary":[50000,60000,70000,80000,90000]

    }
)

In [67]:
data

      Name  Age         City  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000
4      Eve   45      Phoenix   90000

In [70]:
data[data['Age']>25]

      Name  Age         City  Salary
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000
4      Eve   45      Phoenix   90000

In [75]:
data[(data['Age']>25) | (data['Salary']>60000)]

      Name  Age         City  Salary
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000
4      Eve   45      Phoenix   90000

In [77]:
data[data['Age'].isin([30,40,50])]

    Name  Age         City  Salary
1    Bob   30  Los Angeles   60000
3  David   40      Houston   80000

In [78]:
data[data['Age'].between(30,40)]

      Name  Age         City  Salary
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000

In [80]:
data.query('Age > 35')

    Name  Age     City  Salary
3  David   40  Houston   80000
4    Eve   45  Phoenix   90000

In [ ]:
import zipfile
import os

zip_file = r"C:\Users\Vishnu\Downloads\1 - Practice File 1-To -10-Orders Data-20260604T062126Z-3-001.zip"
extract_folder = os.path.splitext(zip_file)[0]

os.makedirs(extract_folder, exist_ok=True)

with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

print(f"Files extracted to:\n{extract_folder}")

Files extracted to:
C:\Users\Vishnu\Downloads\1 - Practice File 1-To -10-Orders Data-20260604T062126Z-3-001

In [88]:
import pandas as pd
import numpy as np

data = {
    "Emp_ID":[101,102,103,104,105,106,106,108,109,110],

    "Name":[
        "Rahul",
        "Aman",
        np.nan,
        "Neha",
        "Priya",
        "Rohit",
        "Rohit",
        "Vikas",
        "Anjali",
        "Karan"
    ],

    "Age":[
        25,
        np.nan,
        28,
        27,
        35,
        40,
        40,
        29,
        np.nan,
        31
    ],

    "Department":[
        "IT",
        "HR",
        "IT",
        np.nan,
        "Finance",
        "HR",
        "HR",
        "IT",
        "Finance",
        "IT"
    ],

    "Salary":[
        50000,
        60000,
        np.nan,
        55000,
        80000,
        70000,
        70000,
        52000,
        75000,
        np.nan
    ],

    "Gender":[
        "M",
        "Male",
        "F",
        "Female",
        "F",
        "M",
        "M",
        "Male",
        "Female",
        "M"
    ]
}

df = pd.DataFrame(data)
print(df)

   Emp_ID    Name   Age Department   Salary  Gender
0     101   Rahul  25.0         IT  50000.0       M
1     102    Aman   NaN         HR  60000.0    Male
2     103     NaN  28.0         IT      NaN       F
3     104    Neha  27.0        NaN  55000.0  Female
4     105   Priya  35.0    Finance  80000.0       F
5     106   Rohit  40.0         HR  70000.0       M
6     106   Rohit  40.0         HR  70000.0       M
7     108   Vikas  29.0         IT  52000.0    Male
8     109  Anjali   NaN    Finance  75000.0  Female
9     110   Karan  31.0         IT      NaN       M

In [89]:
df1=df.copy()

In [90]:
Module 5: Data Cleaning (Most Important for ML)

Missing Values
isnull()
notnull()
fillna()
dropna()
Duplicate Records
duplicated()
drop_duplicates()

SyntaxError: invalid syntax (3803083155.py, line 1)

In [91]:
df.isnull()

   Emp_ID   Name    Age  Department  Salary  Gender
0   False  False  False       False   False   False
1   False  False   True       False   False   False
2   False   True  False       False    True   False
3   False  False  False        True   False   False
4   False  False  False       False   False   False
5   False  False  False       False   False   False
6   False  False  False       False   False   False
7   False  False  False       False   False   False
8   False  False   True       False   False   False
9   False  False  False       False    True   False

In [92]:
df.isnull().sum()

Emp_ID        0
Name          1
Age           2
Department    1
Salary        2
Gender        0
dtype: int64

In [93]:
df.isnull().sum().sum()

np.int64(6)

In [94]:
df[df['Name'].notnull()]

   Emp_ID    Name   Age Department   Salary  Gender
0     101   Rahul  25.0         IT  50000.0       M
1     102    Aman   NaN         HR  60000.0    Male
3     104    Neha  27.0        NaN  55000.0  Female
4     105   Priya  35.0    Finance  80000.0       F
5     106   Rohit  40.0         HR  70000.0       M
6     106   Rohit  40.0         HR  70000.0       M
7     108   Vikas  29.0         IT  52000.0    Male
8     109  Anjali   NaN    Finance  75000.0  Female
9     110   Karan  31.0         IT      NaN       M

In [95]:
df[df['Department'].notnull()]

   Emp_ID    Name   Age Department   Salary  Gender
0     101   Rahul  25.0         IT  50000.0       M
1     102    Aman   NaN         HR  60000.0    Male
2     103     NaN  28.0         IT      NaN       F
4     105   Priya  35.0    Finance  80000.0       F
5     106   Rohit  40.0         HR  70000.0       M
6     106   Rohit  40.0         HR  70000.0       M
7     108   Vikas  29.0         IT  52000.0    Male
8     109  Anjali   NaN    Finance  75000.0  Female
9     110   Karan  31.0         IT      NaN       M

In [96]:
df[df['Salary'].isnull()]

   Emp_ID   Name   Age Department  Salary Gender
2     103    NaN  28.0         IT     NaN      F
9     110  Karan  31.0         IT     NaN      M

In [97]:
df['Name']

0     Rahul
1      Aman
2       NaN
3      Neha
4     Priya
5     Rohit
6     Rohit
7     Vikas
8    Anjali
9     Karan
Name: Name, dtype: object

In [98]:
df['Name']=df['Name'].fillna('Unknown')

In [99]:
df['Name']

0      Rahul
1       Aman
2    Unknown
3       Neha
4      Priya
5      Rohit
6      Rohit
7      Vikas
8     Anjali
9      Karan
Name: Name, dtype: object

In [100]:
df

   Emp_ID     Name   Age Department   Salary  Gender
0     101    Rahul  25.0         IT  50000.0       M
1     102     Aman   NaN         HR  60000.0    Male
2     103  Unknown  28.0         IT      NaN       F
3     104     Neha  27.0        NaN  55000.0  Female
4     105    Priya  35.0    Finance  80000.0       F
5     106    Rohit  40.0         HR  70000.0       M
6     106    Rohit  40.0         HR  70000.0       M
7     108    Vikas  29.0         IT  52000.0    Male
8     109   Anjali   NaN    Finance  75000.0  Female
9     110    Karan  31.0         IT      NaN       M

In [101]:
df['Department']=df['Department'].fillna('Not Assigned')

In [102]:
df["Department"]

0              IT
1              HR
2              IT
3    Not Assigned
4         Finance
5              HR
6              HR
7              IT
8         Finance
9              IT
Name: Department, dtype: object

In [103]:
df

   Emp_ID     Name   Age    Department   Salary  Gender
0     101    Rahul  25.0            IT  50000.0       M
1     102     Aman   NaN            HR  60000.0    Male
2     103  Unknown  28.0            IT      NaN       F
3     104     Neha  27.0  Not Assigned  55000.0  Female
4     105    Priya  35.0       Finance  80000.0       F
5     106    Rohit  40.0            HR  70000.0       M
6     106    Rohit  40.0            HR  70000.0       M
7     108    Vikas  29.0            IT  52000.0    Male
8     109   Anjali   NaN       Finance  75000.0  Female
9     110    Karan  31.0            IT      NaN       M

In [104]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [105]:
df['Age']

0    25.000
1    31.875
2    28.000
3    27.000
4    35.000
5    40.000
6    40.000
7    29.000
8    31.875
9    31.000
Name: Age, dtype: float64

In [106]:
df.isnull().sum()

Emp_ID        0
Name          0
Age           0
Department    0
Salary        2
Gender        0
dtype: int64

In [107]:
df['Salary']=df['Salary'].fillna(df['Salary'].median())

In [108]:
df

   Emp_ID     Name     Age    Department   Salary  Gender
0     101    Rahul  25.000            IT  50000.0       M
1     102     Aman  31.875            HR  60000.0    Male
2     103  Unknown  28.000            IT  65000.0       F
3     104     Neha  27.000  Not Assigned  55000.0  Female
4     105    Priya  35.000       Finance  80000.0       F
5     106    Rohit  40.000            HR  70000.0       M
6     106    Rohit  40.000            HR  70000.0       M
7     108    Vikas  29.000            IT  52000.0    Male
8     109   Anjali  31.875       Finance  75000.0  Female
9     110    Karan  31.000            IT  65000.0       M

In [109]:
df.dropna()

   Emp_ID     Name     Age    Department   Salary  Gender
0     101    Rahul  25.000            IT  50000.0       M
1     102     Aman  31.875            HR  60000.0    Male
2     103  Unknown  28.000            IT  65000.0       F
3     104     Neha  27.000  Not Assigned  55000.0  Female
4     105    Priya  35.000       Finance  80000.0       F
5     106    Rohit  40.000            HR  70000.0       M
6     106    Rohit  40.000            HR  70000.0       M
7     108    Vikas  29.000            IT  52000.0    Male
8     109   Anjali  31.875       Finance  75000.0  Female
9     110    Karan  31.000            IT  65000.0       M

In [110]:
df2=df1.copy()

In [111]:
df1=df1.dropna()

In [112]:
df2

   Emp_ID    Name   Age Department   Salary  Gender
0     101   Rahul  25.0         IT  50000.0       M
1     102    Aman   NaN         HR  60000.0    Male
2     103     NaN  28.0         IT      NaN       F
3     104    Neha  27.0        NaN  55000.0  Female
4     105   Priya  35.0    Finance  80000.0       F
5     106   Rohit  40.0         HR  70000.0       M
6     106   Rohit  40.0         HR  70000.0       M
7     108   Vikas  29.0         IT  52000.0    Male
8     109  Anjali   NaN    Finance  75000.0  Female
9     110   Karan  31.0         IT      NaN       M

In [113]:
df1

   Emp_ID   Name   Age Department   Salary Gender
0     101  Rahul  25.0         IT  50000.0      M
4     105  Priya  35.0    Finance  80000.0      F
5     106  Rohit  40.0         HR  70000.0      M
6     106  Rohit  40.0         HR  70000.0      M
7     108  Vikas  29.0         IT  52000.0   Male

In [114]:
df1=df1.dropna(subset=['Gender'])

In [115]:
df1

   Emp_ID   Name   Age Department   Salary Gender
0     101  Rahul  25.0         IT  50000.0      M
4     105  Priya  35.0    Finance  80000.0      F
5     106  Rohit  40.0         HR  70000.0      M
6     106  Rohit  40.0         HR  70000.0      M
7     108  Vikas  29.0         IT  52000.0   Male

In [116]:
df2.dropna(subset=['Salary'],inplace=True)

In [117]:
df2

   Emp_ID    Name   Age Department   Salary  Gender
0     101   Rahul  25.0         IT  50000.0       M
1     102    Aman   NaN         HR  60000.0    Male
3     104    Neha  27.0        NaN  55000.0  Female
4     105   Priya  35.0    Finance  80000.0       F
5     106   Rohit  40.0         HR  70000.0       M
6     106   Rohit  40.0         HR  70000.0       M
7     108   Vikas  29.0         IT  52000.0    Male
8     109  Anjali   NaN    Finance  75000.0  Female

In [118]:
df2.dropna()

   Emp_ID   Name   Age Department   Salary Gender
0     101  Rahul  25.0         IT  50000.0      M
4     105  Priya  35.0    Finance  80000.0      F
5     106  Rohit  40.0         HR  70000.0      M
6     106  Rohit  40.0         HR  70000.0      M
7     108  Vikas  29.0         IT  52000.0   Male

In [119]:
df[df.duplicated()]

   Emp_ID   Name   Age Department   Salary Gender
6     106  Rohit  40.0         HR  70000.0      M

In [120]:
df=df.drop_duplicates()

In [121]:
df

   Emp_ID     Name     Age    Department   Salary  Gender
0     101    Rahul  25.000            IT  50000.0       M
1     102     Aman  31.875            HR  60000.0    Male
2     103  Unknown  28.000            IT  65000.0       F
3     104     Neha  27.000  Not Assigned  55000.0  Female
4     105    Priya  35.000       Finance  80000.0       F
5     106    Rohit  40.000            HR  70000.0       M
7     108    Vikas  29.000            IT  52000.0    Male
8     109   Anjali  31.875       Finance  75000.0  Female
9     110    Karan  31.000            IT  65000.0       M

In [122]:
df['Gender']=df['Gender'].replace({
    'M':'Male',
    "F":"Female"
})

C:\Users\Vishnu\AppData\Local\Temp\ipykernel_14684\42426902.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender']=df['Gender'].replace({

In [123]:
df["Gender_Code"]=df['Gender'].map({
    'Male':1,
    'Female':0
})

C:\Users\Vishnu\AppData\Local\Temp\ipykernel_14684\3617078555.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender_Code"]=df['Gender'].map({

In [124]:
df

   Emp_ID     Name     Age    Department   Salary  Gender  Gender_Code
0     101    Rahul  25.000            IT  50000.0    Male            1
1     102     Aman  31.875            HR  60000.0    Male            1
2     103  Unknown  28.000            IT  65000.0  Female            0
3     104     Neha  27.000  Not Assigned  55000.0  Female            0
4     105    Priya  35.000       Finance  80000.0  Female            0
5     106    Rohit  40.000            HR  70000.0    Male            1
7     108    Vikas  29.000            IT  52000.0    Male            1
8     109   Anjali  31.875       Finance  75000.0  Female            0
9     110    Karan  31.000            IT  65000.0    Male            1

In [125]:
def category(x):
    if x>=70000:
        return 'High Salary'
    elif x>=50000:
        return 'Medium Salary'
    else:
        return 'Low Salary'
category(75000)

'High Salary'

In [126]:
df['Salary_Category']=df['Salary'].apply(category)

C:\Users\Vishnu\AppData\Local\Temp\ipykernel_14684\1090466285.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Salary_Category']=df['Salary'].apply(category)

In [127]:
df

,Emp_ID,Name,Age,Department,Salary,Gender,Gender_Code,Salary_Category
0,101,Rahul,25.000,IT,50000.0,Male,1,Medium Salary
1,102,Aman,31.875,HR,60000.0,Male,1,Medium Salary
2,103,Unknown,28.000,IT,65000.0,Female,0,Medium Salary
3,104,Neha,27.000,Not Assigned,55000.0,Female,0,Medium Salary
4,105,Priya,35.000,Finance,80000.0,Female,0,High Salary
5,106,Rohit,40.000,HR,70000.0,Male,1,High Salary
7,108,Vikas,29.000,IT,52000.0,Male,1,Medium Salary
8,109,Anjali,31.875,Finance,75000.0,Female,0,High Salary
9,110,Karan,31.000,IT,65000.0,Male,1,Medium Salary

In [128]:
df['Bonus']=df['Salary'].apply(
    lambda x:x*0.10
)

C:\Users\Vishnu\AppData\Local\Temp\ipykernel_14684\867067860.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Bonus']=df['Salary'].apply(

In [129]:
df

,Emp_ID,Name,Age,Department,Salary,Gender,Gender_Code,Salary_Category,Bonus
0,101,Rahul,25.000,IT,50000.0,Male,1,Medium Salary,5000.0
1,102,Aman,31.875,HR,60000.0,Male,1,Medium Salary,6000.0
2,103,Unknown,28.000,IT,65000.0,Female,0,Medium Salary,6500.0
3,104,Neha,27.000,Not Assigned,55000.0,Female,0,Medium Salary,5500.0
4,105,Priya,35.000,Finance,80000.0,Female,0,High Salary,8000.0
5,106,Rohit,40.000,HR,70000.0,Male,1,High Salary,7000.0
7,108,Vikas,29.000,IT,52000.0,Male,1,Medium Salary,5200.0
8,109,Anjali,31.875,Finance,75000.0,Female,0,High Salary,7500.0
9,110,Karan,31.000,IT,65000.0,Male,1,Medium Salary,6500.0

In [130]:
df['Salary']=df['Salary']*1.10

C:\Users\Vishnu\AppData\Local\Temp\ipykernel_14684\3268048160.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Salary']=df['Salary']*1.10

In [131]:
df

,Emp_ID,Name,Age,Department,Salary,Gender,Gender_Code,Salary_Category,Bonus
0,101,Rahul,25.000,IT,55000.0,Male,1,Medium Salary,5000.0
1,102,Aman,31.875,HR,66000.0,Male,1,Medium Salary,6000.0
2,103,Unknown,28.000,IT,71500.0,Female,0,Medium Salary,6500.0
3,104,Neha,27.000,Not Assigned,60500.0,Female,0,Medium Salary,5500.0
4,105,Priya,35.000,Finance,88000.0,Female,0,High Salary,8000.0
5,106,Rohit,40.000,HR,77000.0,Male,1,High Salary,7000.0
7,108,Vikas,29.000,IT,57200.0,Male,1,Medium Salary,5200.0
8,109,Anjali,31.875,Finance,82500.0,Female,0,High Salary,7500.0
9,110,Karan,31.000,IT,71500.0,Male,1,Medium Salary,6500.0

In [132]:
df['Total_salary']=df['Salary']+df['Bonus']

C:\Users\Vishnu\AppData\Local\Temp\ipykernel_14684\2417202670.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Total_salary']=df['Salary']+df['Bonus']

In [133]:
df

,Emp_ID,Name,Age,Department,Salary,Gender,Gender_Code,Salary_Category,Bonus,Total_salary
0,101,Rahul,25.000,IT,55000.0,Male,1,Medium Salary,5000.0,60000.0
1,102,Aman,31.875,HR,66000.0,Male,1,Medium Salary,6000.0,72000.0
2,103,Unknown,28.000,IT,71500.0,Female,0,Medium Salary,6500.0,78000.0
3,104,Neha,27.000,Not Assigned,60500.0,Female,0,Medium Salary,5500.0,66000.0
4,105,Priya,35.000,Finance,88000.0,Female,0,High Salary,8000.0,96000.0
5,106,Rohit,40.000,HR,77000.0,Male,1,High Salary,7000.0,84000.0
7,108,Vikas,29.000,IT,57200.0,Male,1,Medium Salary,5200.0,62400.0
8,109,Anjali,31.875,Finance,82500.0,Female,0,High Salary,7500.0,90000.0
9,110,Karan,31.000,IT,71500.0,Male,1,Medium Salary,6500.0,78000.0

In [134]:
df.dtypes

Emp_ID               int64
Name                object
Age                float64
Department          object
Salary             float64
Gender              object
Gender_Code          int64
Salary_Category     object
Bonus              float64
Total_salary       float64
dtype: object

In [136]:
df.rename(columns={"Emp_ID":"Employee_ID", "Salary":"Monthly_Salary"}, inplace=True)
print(df)
df["Monthly_Salary"] = df["Monthly_Salary"].astype(int)
df.dtypes

   Employee_ID     Name     Age    Department  Monthly_Salary  Gender  \
0          101    Rahul  25.000            IT         55000.0    Male
1          102     Aman  31.875            HR         66000.0    Male
2          103  Unknown  28.000            IT         71500.0  Female
3          104     Neha  27.000  Not Assigned         60500.0  Female
4          105    Priya  35.000       Finance         88000.0  Female
5          106    Rohit  40.000            HR         77000.0    Male
7          108    Vikas  29.000            IT         57200.0    Male
8          109   Anjali  31.875       Finance         82500.0  Female
9          110    Karan  31.000            IT         71500.0    Male

   Gender_Code Salary_Category   Bonus  Total_salary
0            1   Medium Salary  5000.0       60000.0
1            1   Medium Salary  6000.0       72000.0
2            0   Medium Salary  6500.0       78000.0
3            0   Medium Salary  5500.0       66000.0
4            0     High Salary  8000.0       96000.0
5            1     High Salary  7000.0       84000.0
7            1   Medium Salary  5200.0       62400.0
8            0     High Salary  7500.0       90000.0
9            1   Medium Salary  6500.0       78000.0

C:\Users\Vishnu\AppData\Local\Temp\ipykernel_14684\2485641629.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"Emp_ID":"Employee_ID", "Salary":"Monthly_Salary"}, inplace=True)
C:\Users\Vishnu\AppData\Local\Temp\ipykernel_14684\2485641629.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Monthly_Salary"] = df["Monthly_Salary"].astype(int)

Employee_ID          int64
Name                object
Age                float64
Department          object
Monthly_Salary       int64
Gender              object
Gender_Code          int64
Salary_Category     object
Bonus              float64
Total_salary       float64
dtype: object

In [ ]:
Module 7: String Operations
str.upper()
str.lower()
str.strip()
str.contains()
str.split()
str.replace()

Module 8: Date & Time Handling
to_datetime()
Year Extraction
Month Extraction
Day Extraction
Weekday Extraction
Date Difference

In [175]:
import pandas as pd

df = pd.DataFrame({
    "Name":[
        "   rahul   ",
        "AMAN",
        " Neha  ",
        "Priya",
        "ROHIT"
    ],
    "Department":[
        "it",
        "HR",
        "finance",
        "IT",
        "hr"
    ]
}) 

print(df)

          Name Department
0     rahul            it
1         AMAN         HR
2       Neha      finance
3        Priya         IT
4        ROHIT         hr

In [165]:
df

          Name Department
0     rahul            it
1         AMAN         HR
2       Neha      finance
3        Priya         IT
4        ROHIT         hr

In [166]:
df['Name'].str.upper()

0       RAHUL
1           AMAN
2         NEHA
3          PRIYA
4          ROHIT
Name: Name, dtype: object

In [167]:
df['Name'].str.lower()

0       rahul
1           aman
2         neha
3          priya
4          rohit
Name: Name, dtype: object

In [168]:
df['Name'].str.capitalize()

0       rahul
1           Aman
2         neha
3          Priya
4          Rohit
Name: Name, dtype: object

In [169]:
df

          Name Department
0     rahul            it
1         AMAN         HR
2       Neha      finance
3        Priya         IT
4        ROHIT         hr

In [170]:
df['Name Length']=df['Name'].str.len()

In [160]:
df

          Name Department  Name Length
0     rahul            it           11
1         AMAN         HR            4
2        Neha     finance            6
3        Priya         IT            5
4        ROHIT         hr            5

In [171]:
df=df['Name'].str.strip()

In [173]:
df

0    rahul
1     AMAN
2     Neha
3    Priya
4    ROHIT
Name: Name, dtype: object

In [163]:
df

          Name Department  Name Length
0     rahul            it           11
1         AMAN         HR            4
2        Neha     finance            6
3        Priya         IT            5
4        ROHIT         hr            5

In [178]:
df[df['Department'].str.contains('IT',case=False)]

          Name Department
0     rahul            it
3        Priya         IT

In [179]:
df['Department']=df['Department'].str.replace("it","Information Technology",case=False)

In [180]:
df

          Name              Department
0     rahul     Information Technology
1         AMAN                      HR
2       Neha                   finance
3        Priya  Information Technology
4        ROHIT                      hr

In [182]:
email=pd.Series(["rahul@gmail.com","aman@gmail.com"])

In [183]:
email

0    rahul@gmail.com
1     aman@gmail.com
dtype: object

In [184]:
email.str.split("@")

0    [rahul, gmail.com]
1     [aman, gmail.com]
dtype: object