                                    Pandas for Machine Learning Roadmap
    Module 1: Pandas Fundamentals

    Introduction to Pandas
    Series
    DataFrame
    Creating DataFrame
    Reading CSV, Excel, JSON
    Writing CSV, Excel

    Module 2: Data Exploration
    head()
    tail()
    sample()
    shape
    columns
    index
    info()
    describe()
    dtypes

    Module 3: Data Selection
    Column Selection
    Multiple Column Selection
    Row Selection
    loc[]
    iloc[]

Module 4: Data Filtering
Conditional Filtering
Multiple Conditions (&, |)
isin()
between()
query()

Module 5: Data Cleaning (Most Important for ML)

Missing Values
isnull()
notnull()
fillna()
dropna()
Duplicate Records
duplicated()
drop_duplicates()

Module 6: Data Transformation
Add New Columns
Update Existing Columns
Rename Columns
Change Data Types
astype()
replace()
apply()
map()

Module 7: String Operations
str.upper()
str.lower()
str.strip()
str.contains()
str.split()
str.replace()

Module 8: Date & Time Handling
to_datetime()
Year Extraction
Month Extraction
Day Extraction
Weekday Extraction
Date Difference

Module 9: Sorting & Ranking
sort_values()
sort_index()
rank()
nlargest()
nsmallest()

Module 10: Aggregation & Statistics
sum()
mean()
median()
mode()
max()
min()
count()
std()
var()
corr()
Module 11: GroupBy (Very Important)
groupby()
Single Aggregation
Multiple Aggregations
Custom Aggregations
GroupBy + Filter
Module 12: Reshaping Data
Pivot Table
Crosstab
Melt
Stack
Unstack
Module 13: Combining Data
concat()
merge()
Inner Join
Left Join
Right Join
Outer Join
join()

Module 14: Feature Engineering for ML
Creating Features
Binning (cut)
Quantile Binning (qcut)
Encoding Categories
Dummy Variables (get_dummies)
Label Encoding Preparation

In [ ]:
pip install pandas

In [ ]:
import pandas as pd
# How to Create Series
series=pd.Series([1,2,3,4,5])

In [ ]:
print(series)

In [ ]:
print(type(series))

In [ ]:
# DataFrame
# How to Create DataFrame
import pandas as pd
data={'Name':['Alice','Bob','Charlie'],'Age':[25,30,35],'City':['New York','Los Angeles','Chicago']}
print(type(data))
df=pd.DataFrame(data)
print(type(df))

<class 'dict'>
<class 'pandas.core.frame.DataFrame'>

In [ ]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [ ]:
df=pd.read_csv('data.csv')
print(df)

     Roll    Name  Class  Marks
1  Vishnu     MCA    450    NaN
2   Vinit  B.Tech    487    NaN

In [ ]:
dict={'Name':'Alice','Age':25,'City':'New York'}
df=pd.Series(dict)
print(df)

Name       Alice
Age           25
City    New York
dtype: object

In [ ]:
print(type(df))

<class 'pandas.core.series.Series'>

In [ ]:
data=pd.read_excel(r"C:\Users\Vishnu\Desktop\Python_Evening\RL_Task_Scheduling_Dataset.xlsx")

In [ ]:
data

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0          1            91               9         3            28
1          2            12               9         3            55
2          3            56              12         4            16
3          4            83              14         4            59
4          5            57              12         1            79
..       ...           ...             ...       ...           ...
295      296            56              15         4            24
296      297            80               9         3            96
297      298            25               3         3            72
298      299            85               7         2            96
299      300            19               8         2            65

[300 rows x 5 columns]

In [ ]:
data.head()

   Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0        1            91               9         3            28
1        2            12               9         3            55
2        3            56              12         4            16
3        4            83              14         4            59
4        5            57              12         1            79

In [ ]:
data.tail()

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
295      296            56              15         4            24
296      297            80               9         3            96
297      298            25               3         3            72
298      299            85               7         2            96
299      300            19               8         2            65

In [ ]:
data.head(20)

    Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0         1            91               9         3            28
1         2            12               9         3            55
2         3            56              12         4            16
3         4            83              14         4            59
4         5            57              12         1            79
5         6            20              10         5            17
6         7            61               7         2            67
7         8            26              13         5            58
8         9            66               7         4            42
9        10            62               7         2            87
10       11            55               8         4            73
11       12            93              14         1            52
12       13            82              15         3            73
13       14            56               9         1            56
14       15            98              10         3             3
15       16            23               8         3            75
16       17            90               6         1            35
17       18            68               7         4            48
18       19            27               9         1            95
19       20            35               9         1            47

In [ ]:
print(data[10:21])

    Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
10       11            55               8         4            73
11       12            93              14         1            52
12       13            82              15         3            73
13       14            56               9         1            56
14       15            98              10         3             3
15       16            23               8         3            75
16       17            90               6         1            35
17       18            68               7         4            48
18       19            27               9         1            95
19       20            35               9         1            47
20       21            91               3         2            31

In [ ]:
print(data.iloc[10:21,0:4])

    Task_ID  Task_Size_MB  Execution_Time  Priority
10       11            55               8         4
11       12            93              14         1
12       13            82              15         3
13       14            56               9         1
14       15            98              10         3
15       16            23               8         3
16       17            90               6         1
17       18            68               7         4
18       19            27               9         1
19       20            35               9         1
20       21            91               3         2

In [ ]:
data.shape

(300, 5)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Task_ID         300 non-null    int64
 1   Task_Size_MB    300 non-null    int64
 2   Execution_Time  300 non-null    int64
 3   Priority        300 non-null    int64
 4   Arrival_Time    300 non-null    int64
dtypes: int64(5)
memory usage: 11.8 KB

In [ ]:
data.isnull().sum()

Task_ID           0
Task_Size_MB      0
Execution_Time    0
Priority          0
Arrival_Time      0
dtype: int64

In [ ]:
data.columns

Index(['Task_ID', 'Task_Size_MB', 'Execution_Time', 'Priority',
       'Arrival_Time'],
      dtype='object')

In [ ]:
data['Task_Size_MB'].value_counts()

Task_Size_MB
37    9
95    8
56    7
33    7
20    6
     ..
39    1
36    1
84    1
87    1
41    1
Name: count, Length: 87, dtype: int64

In [ ]:
data['Task_Size_MB'].unique()

array([ 91,  12,  56,  83,  57,  20,  61,  26,  66,  62,  55,  93,  82,
        98,  23,  90,  68,  27,  35,  94,  65,  40,  10,  46,  29,  22,
        34,  72,  59,  74,  95,  52,  97,  42,  33,  53,  79,  71,  32,
        11,  51,  18,  43,  50,  60,  85,  15,  21,  37,  13,  17,  14,
        76,  88,  38,  81,  80,  70,  19,  24,  48,  99,  77,  54,  58,
        47,  92,  44,  16,  64,  63,  75,  39,  89,  78,  25, 100,  49,
        69,  31,  30,  36,  67,  96,  84,  87,  41])

In [ ]:
data.index

RangeIndex(start=0, stop=300, step=1)

In [ ]:
data.describe()

          Task_ID  Task_Size_MB  Execution_Time    Priority  Arrival_Time
count  300.000000    300.000000      300.000000  300.000000    300.000000
mean   150.500000     55.170000        8.116667    3.036667     52.006667
std     86.746758     27.261052        4.060132    1.417281     29.338640
min      1.000000     10.000000        1.000000    1.000000      1.000000
25%     75.750000     33.000000        5.000000    2.000000     27.000000
50%    150.500000     55.000000        8.000000    3.000000     53.000000
75%    225.250000     80.000000       11.250000    4.000000     77.000000
max    300.000000    100.000000       15.000000    5.000000    100.000000

In [ ]:
data['Task_Size_MB'].mean()

np.float64(55.17)

In [ ]:
data['Arrival_Time']

0      28
1      55
2      16
3      59
4      79
       ..
295    24
296    96
297    72
298    96
299    65
Name: Arrival_Time, Length: 300, dtype: int64

In [ ]:
data[['Task_Size_MB','Arrival_Time']]

     Task_Size_MB  Arrival_Time
0              91            28
1              12            55
2              56            16
3              83            59
4              57            79
..            ...           ...
295            56            24
296            80            96
297            25            72
298            85            96
299            19            65

[300 rows x 2 columns]

In [ ]:
data.loc[0]

Task_ID            1
Task_Size_MB      91
Execution_Time     9
Priority           3
Arrival_Time      28
Name: 0, dtype: int64

In [ ]:
data.iloc[0]

Task_ID            1
Task_Size_MB      91
Execution_Time     9
Priority           3
Arrival_Time      28
Name: 0, dtype: int64

In [ ]:
data.loc[0,'Arrival_Time']

np.int64(28)

In [ ]:
data.iloc[0,4]

np.int64(28)

In [ ]:
data

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0          1            91               9         3            28
1          2            12               9         3            55
2          3            56              12         4            16
3          4            83              14         4            59
4          5            57              12         1            79
..       ...           ...             ...       ...           ...
295      296            56              15         4            24
296      297            80               9         3            96
297      298            25               3         3            72
298      299            85               7         2            96
299      300            19               8         2            65

[300 rows x 5 columns]

In [ ]:
data.sample(5)

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
69        70            33              12         1            74
287      288            44               5         3            93
185      186            44               8         5            70
290      291            25               7         3            14
91        92            81               6         4             2

In [ ]:
data1=data.copy()

In [ ]:
data1

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0          1            91               9         3            28
1          2            12               9         3            55
2          3            56              12         4            16
3          4            83              14         4            59
4          5            57              12         1            79
..       ...           ...             ...       ...           ...
295      296            56              15         4            24
296      297            80               9         3            96
297      298            25               3         3            72
298      299            85               7         2            96
299      300            19               8         2            65

[300 rows x 5 columns]

In [ ]:
print(type(data1))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
print(data.loc[[295]])

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
295      296            56              15         4            24

In [ ]:
Module 4: Data Filtering
Conditional Filtering
Multiple Conditions (&, |)
isin()
between()
query()

In [ ]:
data

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0          1            91               9         3            28
1          2            12               9         3            55
2          3            56              12         4            16
3          4            83              14         4            59
4          5            57              12         1            79
..       ...           ...             ...       ...           ...
295      296            56              15         4            24
296      297            80               9         3            96
297      298            25               3         3            72
298      299            85               7         2            96
299      300            19               8         2            65

[300 rows x 5 columns]

In [ ]:
Module 4: Data Filtering
Conditional Filtering
Multiple Conditions (&, |)
isin()
between()
query()

In [ ]:
import pandas as pd

data=pd.DataFrame(

    {
        "Name":['Alice','Bob','Charlie','David','Eve'],
        "Age":[25,30,35,40,45],
        "City":['New York','Los Angeles','Chicago','Houston','Phoenix'],
        "Salary":[50000,60000,70000,80000,90000]

    }
)

In [ ]:
data

      Name  Age         City  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000
4      Eve   45      Phoenix   90000

In [ ]:
data[data['Age']>25]

      Name  Age         City  Salary
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000
4      Eve   45      Phoenix   90000

In [ ]:
data[(data['Age']>25) | (data['Salary']>60000)]

      Name  Age         City  Salary
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000
4      Eve   45      Phoenix   90000

In [ ]:
data[data['Age'].isin([30,40,50])]

    Name  Age         City  Salary
1    Bob   30  Los Angeles   60000
3  David   40      Houston   80000

In [ ]:
data[data['Age'].between(30,40)]

      Name  Age         City  Salary
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000

In [ ]:
data.query('Age > 35')

    Name  Age     City  Salary
3  David   40  Houston   80000
4    Eve   45  Phoenix   90000

In [ ]:
import zipfile
import os

zip_file = r"C:\Users\Vishnu\Downloads\1 - Practice File 1-To -10-Orders Data-20260604T062126Z-3-001.zip"
extract_folder = os.path.splitext(zip_file)[0]

os.makedirs(extract_folder, exist_ok=True)

with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

print(f"Files extracted to:\n{extract_folder}")

Files extracted to:
C:\Users\Vishnu\Downloads\1 - Practice File 1-To -10-Orders Data-20260604T062126Z-3-001

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Emp_ID":[101,102,103,104,105,106,106,108,109,110],

    "Name":[
        "Rahul",
        "Aman",
        np.nan,
        "Neha",
        "Priya",
        "Rohit",
        "Rohit",
        "Vikas",
        "Anjali",
        "Karan"
    ],

    "Age":[
        25,
        np.nan,
        28,
        27,
        35,
        40,
        40,
        29,
        np.nan,
        31
    ],

    "Department":[
        "IT",
        "HR",
        "IT",
        np.nan,
        "Finance",
        "HR",
        "HR",
        "IT",
        "Finance",
        "IT"
    ],

    "Salary":[
        50000,
        60000,
        np.nan,
        55000,
        80000,
        70000,
        70000,
        52000,
        75000,
        np.nan
    ],

    "Gender":[
        "M",
        "Male",
        "F",
        "Female",
        "F",
        "M",
        "M",
        "Male",
        "Female",
        "M"
    ]
}

df = pd.DataFrame(data)
print(df)

   Emp_ID    Name   Age Department   Salary  Gender
0     101   Rahul  25.0         IT  50000.0       M
1     102    Aman   NaN         HR  60000.0    Male
2     103     NaN  28.0         IT      NaN       F
3     104    Neha  27.0        NaN  55000.0  Female
4     105   Priya  35.0    Finance  80000.0       F
5     106   Rohit  40.0         HR  70000.0       M
6     106   Rohit  40.0         HR  70000.0       M
7     108   Vikas  29.0         IT  52000.0    Male
8     109  Anjali   NaN    Finance  75000.0  Female
9     110   Karan  31.0         IT      NaN       M

In [ ]:
df1=df.copy()

In [ ]:
Module 5: Data Cleaning (Most Important for ML)

Missing Values
isnull()
notnull()
fillna()
dropna()
Duplicate Records
duplicated()
drop_duplicates()

SyntaxError: invalid syntax (3803083155.py, line 1)

In [ ]:
df.isnull()

   Emp_ID   Name    Age  Department  Salary  Gender
0   False  False  False       False   False   False
1   False  False   True       False   False   False
2   False   True  False       False    True   False
3   False  False  False        True   False   False
4   False  False  False       False   False   False
5   False  False  False       False   False   False
6   False  False  False       False   False   False
7   False  False  False       False   False   False
8   False  False   True       False   False   False
9   False  False  False       False    True   False

In [ ]:
df.isnull().sum()

Emp_ID        0
Name          1
Age           2
Department    1
Salary        2
Gender        0
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(6)

In [ ]:
df[df['Name'].notnull()]

   Emp_ID    Name   Age Department   Salary  Gender
0     101   Rahul  25.0         IT  50000.0       M
1     102    Aman   NaN         HR  60000.0    Male
3     104    Neha  27.0        NaN  55000.0  Female
4     105   Priya  35.0    Finance  80000.0       F
5     106   Rohit  40.0         HR  70000.0       M
6     106   Rohit  40.0         HR  70000.0       M
7     108   Vikas  29.0         IT  52000.0    Male
8     109  Anjali   NaN    Finance  75000.0  Female
9     110   Karan  31.0         IT      NaN       M

In [ ]:
df[df['Department'].notnull()]

   Emp_ID    Name   Age Department   Salary  Gender
0     101   Rahul  25.0         IT  50000.0       M
1     102    Aman   NaN         HR  60000.0    Male
2     103     NaN  28.0         IT      NaN       F
4     105   Priya  35.0    Finance  80000.0       F
5     106   Rohit  40.0         HR  70000.0       M
6     106   Rohit  40.0         HR  70000.0       M
7     108   Vikas  29.0         IT  52000.0    Male
8     109  Anjali   NaN    Finance  75000.0  Female
9     110   Karan  31.0         IT      NaN       M

In [ ]:
df[df['Salary'].isnull()]

   Emp_ID   Name   Age Department  Salary Gender
2     103    NaN  28.0         IT     NaN      F
9     110  Karan  31.0         IT     NaN      M

In [ ]:
df['Name']

0     Rahul
1      Aman
2       NaN
3      Neha
4     Priya
5     Rohit
6     Rohit
7     Vikas
8    Anjali
9     Karan
Name: Name, dtype: object

In [ ]:
df['Name']=df['Name'].fillna('Unknown')

In [ ]:
df['Name']

0      Rahul
1       Aman
2    Unknown
3       Neha
4      Priya
5      Rohit
6      Rohit
7      Vikas
8     Anjali
9      Karan
Name: Name, dtype: object

In [ ]:
df

   Emp_ID     Name   Age Department   Salary  Gender
0     101    Rahul  25.0         IT  50000.0       M
1     102     Aman   NaN         HR  60000.0    Male
2     103  Unknown  28.0         IT      NaN       F
3     104     Neha  27.0        NaN  55000.0  Female
4     105    Priya  35.0    Finance  80000.0       F
5     106    Rohit  40.0         HR  70000.0       M
6     106    Rohit  40.0         HR  70000.0       M
7     108    Vikas  29.0         IT  52000.0    Male
8     109   Anjali   NaN    Finance  75000.0  Female
9     110    Karan  31.0         IT      NaN       M

In [ ]:
df['Department']=df['Department'].fillna('Not Assigned')

In [ ]:
df["Department"]

0              IT
1              HR
2              IT
3    Not Assigned
4         Finance
5              HR
6              HR
7              IT
8         Finance
9              IT
Name: Department, dtype: object

In [ ]:
df

   Emp_ID     Name   Age    Department   Salary  Gender
0     101    Rahul  25.0            IT  50000.0       M
1     102     Aman   NaN            HR  60000.0    Male
2     103  Unknown  28.0            IT      NaN       F
3     104     Neha  27.0  Not Assigned  55000.0  Female
4     105    Priya  35.0       Finance  80000.0       F
5     106    Rohit  40.0            HR  70000.0       M
6     106    Rohit  40.0            HR  70000.0       M
7     108    Vikas  29.0            IT  52000.0    Male
8     109   Anjali   NaN       Finance  75000.0  Female
9     110    Karan  31.0            IT      NaN       M

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [ ]:
df['Age']

0    25.000
1    31.875
2    28.000
3    27.000
4    35.000
5    40.000
6    40.000
7    29.000
8    31.875
9    31.000
Name: Age, dtype: float64

In [ ]:
df.isnull().sum()

Emp_ID        0
Name          0
Age           0
Department    0
Salary        2
Gender        0
dtype: int64

In [ ]:
df['Salary']=df['Salary'].fillna(df['Salary'].median())

In [ ]:
df

   Emp_ID     Name     Age    Department   Salary  Gender
0     101    Rahul  25.000            IT  50000.0       M
1     102     Aman  31.875            HR  60000.0    Male
2     103  Unknown  28.000            IT  65000.0       F
3     104     Neha  27.000  Not Assigned  55000.0  Female
4     105    Priya  35.000       Finance  80000.0       F
5     106    Rohit  40.000            HR  70000.0       M
6     106    Rohit  40.000            HR  70000.0       M
7     108    Vikas  29.000            IT  52000.0    Male
8     109   Anjali  31.875       Finance  75000.0  Female
9     110    Karan  31.000            IT  65000.0       M

In [ ]:
df.dropna()

   Emp_ID     Name     Age    Department   Salary  Gender
0     101    Rahul  25.000            IT  50000.0       M
1     102     Aman  31.875            HR  60000.0    Male
2     103  Unknown  28.000            IT  65000.0       F
3     104     Neha  27.000  Not Assigned  55000.0  Female
4     105    Priya  35.000       Finance  80000.0       F
5     106    Rohit  40.000            HR  70000.0       M
6     106    Rohit  40.000            HR  70000.0       M
7     108    Vikas  29.000            IT  52000.0    Male
8     109   Anjali  31.875       Finance  75000.0  Female
9     110    Karan  31.000            IT  65000.0       M

In [ ]:
df2=df1.copy()

In [ ]:
df1=df1.dropna()

In [ ]:
df2

   Emp_ID    Name   Age Department   Salary  Gender
0     101   Rahul  25.0         IT  50000.0       M
1     102    Aman   NaN         HR  60000.0    Male
2     103     NaN  28.0         IT      NaN       F
3     104    Neha  27.0        NaN  55000.0  Female
4     105   Priya  35.0    Finance  80000.0       F
5     106   Rohit  40.0         HR  70000.0       M
6     106   Rohit  40.0         HR  70000.0       M
7     108   Vikas  29.0         IT  52000.0    Male
8     109  Anjali   NaN    Finance  75000.0  Female
9     110   Karan  31.0         IT      NaN       M

In [ ]:
df1

   Emp_ID   Name   Age Department   Salary Gender
0     101  Rahul  25.0         IT  50000.0      M
4     105  Priya  35.0    Finance  80000.0      F
5     106  Rohit  40.0         HR  70000.0      M
6     106  Rohit  40.0         HR  70000.0      M
7     108  Vikas  29.0         IT  52000.0   Male

In [ ]:
df1=df1.dropna(subset=['Gender'])

In [ ]:
df1

   Emp_ID   Name   Age Department   Salary Gender
0     101  Rahul  25.0         IT  50000.0      M
4     105  Priya  35.0    Finance  80000.0      F
5     106  Rohit  40.0         HR  70000.0      M
6     106  Rohit  40.0         HR  70000.0      M
7     108  Vikas  29.0         IT  52000.0   Male

In [ ]:
df2.dropna(subset=['Salary'],inplace=True)

In [ ]:
df2

   Emp_ID    Name   Age Department   Salary  Gender
0     101   Rahul  25.0         IT  50000.0       M
1     102    Aman   NaN         HR  60000.0    Male
3     104    Neha  27.0        NaN  55000.0  Female
4     105   Priya  35.0    Finance  80000.0       F
5     106   Rohit  40.0         HR  70000.0       M
6     106   Rohit  40.0         HR  70000.0       M
7     108   Vikas  29.0         IT  52000.0    Male
8     109  Anjali   NaN    Finance  75000.0  Female

In [ ]:
df2.dropna()

   Emp_ID   Name   Age Department   Salary Gender
0     101  Rahul  25.0         IT  50000.0      M
4     105  Priya  35.0    Finance  80000.0      F
5     106  Rohit  40.0         HR  70000.0      M
6     106  Rohit  40.0         HR  70000.0      M
7     108  Vikas  29.0         IT  52000.0   Male

In [ ]:
df[df.duplicated()]

   Emp_ID   Name   Age Department   Salary Gender
6     106  Rohit  40.0         HR  70000.0      M

In [ ]:
df=df.drop_duplicates()

In [ ]:
df

   Emp_ID     Name     Age    Department   Salary  Gender
0     101    Rahul  25.000            IT  50000.0       M
1     102     Aman  31.875            HR  60000.0    Male
2     103  Unknown  28.000            IT  65000.0       F
3     104     Neha  27.000  Not Assigned  55000.0  Female
4     105    Priya  35.000       Finance  80000.0       F
5     106    Rohit  40.000            HR  70000.0       M
7     108    Vikas  29.000            IT  52000.0    Male
8     109   Anjali  31.875       Finance  75000.0  Female
9     110    Karan  31.000            IT  65000.0       M

In [ ]:
df['Gender']=df['Gender'].replace({
    'M':'Male',
    "F":"Female"
})

C:\Users\Vishnu\AppData\Local\Temp\ipykernel_14684\42426902.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender']=df['Gender'].replace({

In [ ]:
df["Gender_Code"]=df['Gender'].map({
    'Male':1,
    'Female':0
})

C:\Users\Vishnu\AppData\Local\Temp\ipykernel_14684\3617078555.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender_Code"]=df['Gender'].map({

In [ ]:
df

   Emp_ID     Name     Age    Department   Salary  Gender  Gender_Code
0     101    Rahul  25.000            IT  50000.0    Male            1
1     102     Aman  31.875            HR  60000.0    Male            1
2     103  Unknown  28.000            IT  65000.0  Female            0
3     104     Neha  27.000  Not Assigned  55000.0  Female            0
4     105    Priya  35.000       Finance  80000.0  Female            0
5     106    Rohit  40.000            HR  70000.0    Male            1
7     108    Vikas  29.000            IT  52000.0    Male            1
8     109   Anjali  31.875       Finance  75000.0  Female            0
9     110    Karan  31.000            IT  65000.0    Male            1

In [ ]:
def category(x):
    if x>=70000:
        return 'High Salary'
    elif x>=50000:
        return 'Medium Salary'
    else:
        return 'Low Salary'
category(75000)

'High Salary'

In [ ]:
df['Salary_Category']=df['Salary'].apply(category)

C:\Users\Vishnu\AppData\Local\Temp\ipykernel_14684\1090466285.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Salary_Category']=df['Salary'].apply(category)

In [ ]:
df

,Emp_ID,Name,Age,Department,Salary,Gender,Gender_Code,Salary_Category
0,101,Rahul,25.000,IT,50000.0,Male,1,Medium Salary
1,102,Aman,31.875,HR,60000.0,Male,1,Medium Salary
2,103,Unknown,28.000,IT,65000.0,Female,0,Medium Salary
3,104,Neha,27.000,Not Assigned,55000.0,Female,0,Medium Salary
4,105,Priya,35.000,Finance,80000.0,Female,0,High Salary
5,106,Rohit,40.000,HR,70000.0,Male,1,High Salary
7,108,Vikas,29.000,IT,52000.0,Male,1,Medium Salary
8,109,Anjali,31.875,Finance,75000.0,Female,0,High Salary
9,110,Karan,31.000,IT,65000.0,Male,1,Medium Salary

In [ ]:
df['Bonus']=df['Salary'].apply(
    lambda x:x*0.10
)

C:\Users\Vishnu\AppData\Local\Temp\ipykernel_14684\867067860.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Bonus']=df['Salary'].apply(

In [ ]:
df

,Emp_ID,Name,Age,Department,Salary,Gender,Gender_Code,Salary_Category,Bonus
0,101,Rahul,25.000,IT,50000.0,Male,1,Medium Salary,5000.0
1,102,Aman,31.875,HR,60000.0,Male,1,Medium Salary,6000.0
2,103,Unknown,28.000,IT,65000.0,Female,0,Medium Salary,6500.0
3,104,Neha,27.000,Not Assigned,55000.0,Female,0,Medium Salary,5500.0
4,105,Priya,35.000,Finance,80000.0,Female,0,High Salary,8000.0
5,106,Rohit,40.000,HR,70000.0,Male,1,High Salary,7000.0
7,108,Vikas,29.000,IT,52000.0,Male,1,Medium Salary,5200.0
8,109,Anjali,31.875,Finance,75000.0,Female,0,High Salary,7500.0
9,110,Karan,31.000,IT,65000.0,Male,1,Medium Salary,6500.0

In [ ]:
df['Salary']=df['Salary']*1.10

C:\Users\Vishnu\AppData\Local\Temp\ipykernel_14684\3268048160.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Salary']=df['Salary']*1.10

In [ ]:
df

,Emp_ID,Name,Age,Department,Salary,Gender,Gender_Code,Salary_Category,Bonus
0,101,Rahul,25.000,IT,55000.0,Male,1,Medium Salary,5000.0
1,102,Aman,31.875,HR,66000.0,Male,1,Medium Salary,6000.0
2,103,Unknown,28.000,IT,71500.0,Female,0,Medium Salary,6500.0
3,104,Neha,27.000,Not Assigned,60500.0,Female,0,Medium Salary,5500.0
4,105,Priya,35.000,Finance,88000.0,Female,0,High Salary,8000.0
5,106,Rohit,40.000,HR,77000.0,Male,1,High Salary,7000.0
7,108,Vikas,29.000,IT,57200.0,Male,1,Medium Salary,5200.0
8,109,Anjali,31.875,Finance,82500.0,Female,0,High Salary,7500.0
9,110,Karan,31.000,IT,71500.0,Male,1,Medium Salary,6500.0

In [ ]:
df['Total_salary']=df['Salary']+df['Bonus']

C:\Users\Vishnu\AppData\Local\Temp\ipykernel_14684\2417202670.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Total_salary']=df['Salary']+df['Bonus']

In [ ]:
df

,Emp_ID,Name,Age,Department,Salary,Gender,Gender_Code,Salary_Category,Bonus,Total_salary
0,101,Rahul,25.000,IT,55000.0,Male,1,Medium Salary,5000.0,60000.0
1,102,Aman,31.875,HR,66000.0,Male,1,Medium Salary,6000.0,72000.0
2,103,Unknown,28.000,IT,71500.0,Female,0,Medium Salary,6500.0,78000.0
3,104,Neha,27.000,Not Assigned,60500.0,Female,0,Medium Salary,5500.0,66000.0
4,105,Priya,35.000,Finance,88000.0,Female,0,High Salary,8000.0,96000.0
5,106,Rohit,40.000,HR,77000.0,Male,1,High Salary,7000.0,84000.0
7,108,Vikas,29.000,IT,57200.0,Male,1,Medium Salary,5200.0,62400.0
8,109,Anjali,31.875,Finance,82500.0,Female,0,High Salary,7500.0,90000.0
9,110,Karan,31.000,IT,71500.0,Male,1,Medium Salary,6500.0,78000.0

In [ ]:
df.dtypes

Emp_ID               int64
Name                object
Age                float64
Department          object
Salary             float64
Gender              object
Gender_Code          int64
Salary_Category     object
Bonus              float64
Total_salary       float64
dtype: object

In [ ]:
df.rename(columns={"Emp_ID":"Employee_ID", "Salary":"Monthly_Salary"}, inplace=True)
print(df)
df["Monthly_Salary"] = df["Monthly_Salary"].astype(int)
df.dtypes

   Employee_ID     Name     Age    Department  Monthly_Salary  Gender  \
0          101    Rahul  25.000            IT         55000.0    Male
1          102     Aman  31.875            HR         66000.0    Male
2          103  Unknown  28.000            IT         71500.0  Female
3          104     Neha  27.000  Not Assigned         60500.0  Female
4          105    Priya  35.000       Finance         88000.0  Female
5          106    Rohit  40.000            HR         77000.0    Male
7          108    Vikas  29.000            IT         57200.0    Male
8          109   Anjali  31.875       Finance         82500.0  Female
9          110    Karan  31.000            IT         71500.0    Male

   Gender_Code Salary_Category   Bonus  Total_salary
0            1   Medium Salary  5000.0       60000.0
1            1   Medium Salary  6000.0       72000.0
2            0   Medium Salary  6500.0       78000.0
3            0   Medium Salary  5500.0       66000.0
4            0     High Salary  8000.0       96000.0
5            1     High Salary  7000.0       84000.0
7            1   Medium Salary  5200.0       62400.0
8            0     High Salary  7500.0       90000.0
9            1   Medium Salary  6500.0       78000.0

C:\Users\Vishnu\AppData\Local\Temp\ipykernel_14684\2485641629.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"Emp_ID":"Employee_ID", "Salary":"Monthly_Salary"}, inplace=True)
C:\Users\Vishnu\AppData\Local\Temp\ipykernel_14684\2485641629.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Monthly_Salary"] = df["Monthly_Salary"].astype(int)

Employee_ID          int64
Name                object
Age                float64
Department          object
Monthly_Salary       int64
Gender              object
Gender_Code          int64
Salary_Category     object
Bonus              float64
Total_salary       float64
dtype: object

In [ ]:
Module 7: String Operations
str.upper()
str.lower()
str.strip()
str.contains()
str.split()
str.replace()

Module 8: Date & Time Handling
to_datetime()
Year Extraction
Month Extraction
Day Extraction
Weekday Extraction
Date Difference

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name":[
        "   rahul   ",
        "AMAN",
        " Neha  ",
        "Priya",
        "ROHIT"
    ],
    "Department":[
        "it",
        "HR",
        "finance",
        "IT",
        "hr"
    ]
}) 

print(df)

          Name Department
0     rahul            it
1         AMAN         HR
2       Neha      finance
3        Priya         IT
4        ROHIT         hr

In [ ]:
df

          Name Department
0     rahul            it
1         AMAN         HR
2       Neha      finance
3        Priya         IT
4        ROHIT         hr

In [ ]:
df['Name'].str.upper()

0       RAHUL
1           AMAN
2         NEHA
3          PRIYA
4          ROHIT
Name: Name, dtype: object

In [ ]:
df['Name'].str.lower()

0       rahul
1           aman
2         neha
3          priya
4          rohit
Name: Name, dtype: object

In [ ]:
df['Name'].str.capitalize()

0       rahul
1           Aman
2         neha
3          Priya
4          Rohit
Name: Name, dtype: object

In [ ]:
df

          Name Department
0     rahul            it
1         AMAN         HR
2       Neha      finance
3        Priya         IT
4        ROHIT         hr

In [ ]:
df['Name Length']=df['Name'].str.len()

In [ ]:
df

          Name Department  Name Length
0     rahul            it           11
1         AMAN         HR            4
2        Neha     finance            6
3        Priya         IT            5
4        ROHIT         hr            5

In [ ]:
df=df['Name'].str.strip()

In [ ]:
df

0    rahul
1     AMAN
2     Neha
3    Priya
4    ROHIT
Name: Name, dtype: object

In [ ]:
df

          Name Department  Name Length
0     rahul            it           11
1         AMAN         HR            4
2        Neha     finance            6
3        Priya         IT            5
4        ROHIT         hr            5

In [ ]:
df[df['Department'].str.contains('IT',case=False)]

          Name Department
0     rahul            it
3        Priya         IT

In [ ]:
df['Department']=df['Department'].str.replace("it","Information Technology",case=False)

In [ ]:
df

          Name              Department
0     rahul     Information Technology
1         AMAN                      HR
2       Neha                   finance
3        Priya  Information Technology
4        ROHIT                      hr

In [ ]:
email=pd.Series(["rahul@gmail.com","aman@gmail.com"])

In [ ]:
email

0    rahul@gmail.com
1     aman@gmail.com
dtype: object

In [ ]:
email.str.split("@")

0    [rahul, gmail.com]
1     [aman, gmail.com]
dtype: object

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Customer_ID":[
        1001,1002,1003,1004,1005,
        1006,1007,1008,1009,1010
    ],

    "Customer_Name":[
        "Rahul","Aman","Neha","Priya","Rohit",
        "Vikas","Anjali","Karan","Pooja","Amit"
    ],

    "Signup_Date":[
        "2022-01-15",
        "15/03/2022",
        "Apr 10, 2022",
        "2022/05/20",
        np.nan,
        "2022-06-31",
        "07-25-2022",
        "2022-08-15",
        "September 5, 2022",
        "2022.10.10"
    ],

    "Last_Login_Date":[
        "2024-01-10",
        "2024-02-15",
        "2024-03-05",
        np.nan,
        "2024-04-20",
        "2024-05-25",
        "2024-06-10",
        "2024-07-15",
        "2024-08-05",
        "2024-09-01"
    ],

    "Subscription_End":[
        "2024-12-31",
        "2024-11-30",
        "2024-10-15",
        "2024-09-20",
        "2024-08-31",
        np.nan,
        "2024-07-31",
        "2024-06-30",
        "2024-05-31",
        "2024-04-30"
    ],

    "Monthly_Charges":[
        499,699,899,599,799,
        999,549,649,749,899
    ],

    "Churn":[
        0,1,0,1,0,
        1,0,1,0,1
    ]
}

telecome = pd.DataFrame(data)

print(telecome)

   Customer_ID Customer_Name        Signup_Date Last_Login_Date  \
0         1001         Rahul         2022-01-15      2024-01-10
1         1002          Aman         15/03/2022      2024-02-15
2         1003          Neha       Apr 10, 2022      2024-03-05
3         1004         Priya         2022/05/20             NaN
4         1005         Rohit                NaN      2024-04-20
5         1006         Vikas         2022-06-31      2024-05-25
6         1007        Anjali         07-25-2022      2024-06-10
7         1008         Karan         2022-08-15      2024-07-15
8         1009         Pooja  September 5, 2022      2024-08-05
9         1010          Amit         2022.10.10      2024-09-01

  Subscription_End  Monthly_Charges  Churn
0       2024-12-31              499      0
1       2024-11-30              699      1
2       2024-10-15              899      0
3       2024-09-20              599      1
4       2024-08-31              799      0
5              NaN              999      1
6       2024-07-31              549      0
7       2024-06-30              649      1
8       2024-05-31              749      0
9       2024-04-30              899      1

In [ ]:
telecome

,Customer_ID,Customer_Name,Signup_Date,Last_Login_Date,Subscription_End,Monthly_Charges,Churn
0,1001,Rahul,2022-01-15,2024-01-10,2024-12-31,499,0
1,1002,Aman,15/03/2022,2024-02-15,2024-11-30,699,1
2,1003,Neha,"Apr 10, 2022",2024-03-05,2024-10-15,899,0
3,1004,Priya,2022/05/20,NaN,2024-09-20,599,1
4,1005,Rohit,NaN,2024-04-20,2024-08-31,799,0
5,1006,Vikas,2022-06-31,2024-05-25,NaN,999,1
6,1007,Anjali,07-25-2022,2024-06-10,2024-07-31,549,0
7,1008,Karan,2022-08-15,2024-07-15,2024-06-30,649,1
8,1009,Pooja,"September 5, 2022",2024-08-05,2024-05-31,749,0
9,1010,Amit,2022.10.10,2024-09-01,2024-04-30,899,1

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Emp_ID":[101,102,103,104,105,106,107,108,109,110],

    "Name":[
        "Rahul",
        "Aman",
        "Neha",
        "Priya",
        "Rohit",
        "Vikas",
        "Anjali",
        "Karan",
        "Pooja",
        "Amit"
    ],

    "Join_Date":[
        "2023-01-15",
        "15/02/2023",
        "Mar 10, 2023",
        "2023/04/20",
        np.nan,
        "2023-06-31",
        "07-15-2023",
        "2023-08-25",
        "September 5, 2023",
        "2023.10.10"
    ],

    "Last_Login":[
        "2024-01-10 09:30:00",
        "2024-02-15 10:15:00",
        "2024-03-05 08:45:00",
        np.nan,
        "2024-04-20 11:00:00",
        "2024-05-25 09:20:00",
        "2024-06-10 08:30:00",
        "2024-07-15 10:00:00",
        "2024-08-05 09:45:00",
        "2024-09-01 11:15:00"
    ]
}

hr = pd.DataFrame(data)

print(hr)

   Emp_ID    Name          Join_Date           Last_Login
0     101   Rahul         2023-01-15  2024-01-10 09:30:00
1     102    Aman         15/02/2023  2024-02-15 10:15:00
2     103    Neha       Mar 10, 2023  2024-03-05 08:45:00
3     104   Priya         2023/04/20                  NaN
4     105   Rohit                NaN  2024-04-20 11:00:00
5     106   Vikas         2023-06-31  2024-05-25 09:20:00
6     107  Anjali         07-15-2023  2024-06-10 08:30:00
7     108   Karan         2023-08-25  2024-07-15 10:00:00
8     109   Pooja  September 5, 2023  2024-08-05 09:45:00
9     110    Amit         2023.10.10  2024-09-01 11:15:00

In [ ]:
hr.dtypes

Emp_ID         int64
Name          object
Join_Date     object
Last_Login    object
dtype: object

In [ ]:
df

,Customer_ID,Customer_Name,Signup_Date,Last_Login_Date,Subscription_End,Monthly_Charges,Churn
0,1001,Rahul,2022-01-15,2024-01-10,2024-12-31,499,0
1,1002,Aman,15/03/2022,2024-02-15,2024-11-30,699,1
2,1003,Neha,"Apr 10, 2022",2024-03-05,2024-10-15,899,0
3,1004,Priya,2022/05/20,NaN,2024-09-20,599,1
4,1005,Rohit,NaN,2024-04-20,2024-08-31,799,0
5,1006,Vikas,2022-06-31,2024-05-25,NaN,999,1
6,1007,Anjali,07-25-2022,2024-06-10,2024-07-31,549,0
7,1008,Karan,2022-08-15,2024-07-15,2024-06-30,649,1
8,1009,Pooja,"September 5, 2022",2024-08-05,2024-05-31,749,0
9,1010,Amit,2022.10.10,2024-09-01,2024-04-30,899,1

In [ ]:
hr['Join_Date']=hr['Join_Date'].str.replace("/","-",case=False)
hr['Join_Date']=hr['Join_Date'].str.replace(".","-",case=False)

In [ ]:
hr

   Emp_ID    Name          Join_Date           Last_Login
0     101   Rahul         2023-01-15  2024-01-10 09:30:00
1     102    Aman         15-02-2023  2024-02-15 10:15:00
2     103    Neha       Mar 10, 2023  2024-03-05 08:45:00
3     104   Priya         2023-04-20                  NaN
4     105   Rohit                NaN  2024-04-20 11:00:00
5     106   Vikas         2023-06-31  2024-05-25 09:20:00
6     107  Anjali         07-15-2023  2024-06-10 08:30:00
7     108   Karan         2023-08-25  2024-07-15 10:00:00
8     109   Pooja  September 5, 2023  2024-08-05 09:45:00
9     110    Amit         2023-10-10  2024-09-01 11:15:00

In [ ]:
hr['Join_Date']=hr['Join_Date'].str.replace(".","-",case=False)

Module 8: Date & Time Handling
to_datetime()
Year Extraction
Month Extraction
Day Extraction
Weekday Extraction
Date Difference

In [ ]:
hr.dtypes

Emp_ID         int64
Name          object
Join_Date     object
Last_Login    object
dtype: object

In [ ]:
hr['Join_Date']=pd.to_datetime(hr['Join_Date'],errors='coerce',format="mixed")

In [ ]:
hr

   Emp_ID    Name  Join_Date           Last_Login
0     101   Rahul 2023-01-15  2024-01-10 09:30:00
1     102    Aman 2023-02-15  2024-02-15 10:15:00
2     103    Neha 2023-03-10  2024-03-05 08:45:00
3     104   Priya 2023-04-20                  NaN
4     105   Rohit        NaT  2024-04-20 11:00:00
5     106   Vikas        NaT  2024-05-25 09:20:00
6     107  Anjali 2023-07-15  2024-06-10 08:30:00
7     108   Karan 2023-08-25  2024-07-15 10:00:00
8     109   Pooja 2023-09-05  2024-08-05 09:45:00
9     110    Amit 2023-10-10  2024-09-01 11:15:00

In [ ]:
hr['Updated_Last_Login']=pd.to_datetime(hr['Last_Login'],errors='coerce').dt.date

In [ ]:

hr.dtypes

Emp_ID                 int64
Name                  object
Join_Date     datetime64[ns]
Last_Login            object
dtype: object

In [ ]:
hr['Last_Login']=pd.to_datetime(hr['Last_Login'],errors='coerce')

In [ ]:
hr['Updated_Last_Login']=pd.to_datetime(hr['Last_Login'],errors='coerce').dt.date

In [ ]:
hr.dtypes

Emp_ID                         int64
Name                          object
Join_Date             datetime64[ns]
Last_Login            datetime64[ns]
Updated_Last_Login            object
dtype: object

In [ ]:
hr['Join_Date'].dt.year
hr['Join_Date'].dt.month

0     1.0
1     2.0
2     3.0
3     4.0
4     NaN
5     NaN
6     7.0
7     8.0
8     9.0
9    10.0
Name: Join_Date, dtype: float64

In [ ]:
hr['Join_Date']=hr['Join_Date'].fillna(hr['Join_Date'].median())

In [ ]:
hr['Last_Login']=hr['Last_Login'].fillna(hr['Last_Login'].median())

In [ ]:
hr

   Emp_ID    Name  Join_Date          Last_Login Updated_Last_Login
0     101   Rahul 2023-01-15 2024-01-10 09:30:00         2024-01-10
1     102    Aman 2023-02-15 2024-02-15 10:15:00         2024-02-15
2     103    Neha 2023-03-10 2024-03-05 08:45:00         2024-03-05
3     104   Priya 2023-04-20 2024-05-25 09:20:00                NaT
4     105   Rohit 2023-06-02 2024-04-20 11:00:00         2024-04-20
5     106   Vikas 2023-06-02 2024-05-25 09:20:00         2024-05-25
6     107  Anjali 2023-07-15 2024-06-10 08:30:00         2024-06-10
7     108   Karan 2023-08-25 2024-07-15 10:00:00         2024-07-15
8     109   Pooja 2023-09-05 2024-08-05 09:45:00         2024-08-05
9     110    Amit 2023-10-10 2024-09-01 11:15:00         2024-09-01

In [ ]:
hr['Year']=hr['Join_Date'].dt.year
hr['Month']=hr['Join_Date'].dt.month
hr['Day']=hr['Join_Date'].dt.day
hr['Weekday_Name']=hr['Join_Date'].dt.day_name()

In [ ]:
hr

,Emp_ID,Name,Join_Date,Last_Login,Updated_Last_Login,Year,Month,Day,Weekday,Weekday_Name
0,101,Rahul,2023-01-15,2024-01-10 09:30:00,2024-01-10,2023,1,15,Sunday,Sunday
1,102,Aman,2023-02-15,2024-02-15 10:15:00,2024-02-15,2023,2,15,Wednesday,Wednesday
2,103,Neha,2023-03-10,2024-03-05 08:45:00,2024-03-05,2023,3,10,Friday,Friday
3,104,Priya,2023-04-20,2024-05-25 09:20:00,NaT,2023,4,20,Thursday,Thursday
4,105,Rohit,2023-06-02,2024-04-20 11:00:00,2024-04-20,2023,6,2,Friday,Friday
5,106,Vikas,2023-06-02,2024-05-25 09:20:00,2024-05-25,2023,6,2,Friday,Friday
6,107,Anjali,2023-07-15,2024-06-10 08:30:00,2024-06-10,2023,7,15,Saturday,Saturday
7,108,Karan,2023-08-25,2024-07-15 10:00:00,2024-07-15,2023,8,25,Friday,Friday
8,109,Pooja,2023-09-05,2024-08-05 09:45:00,2024-08-05,2023,9,5,Tuesday,Tuesday
9,110,Amit,2023-10-10,2024-09-01 11:15:00,2024-09-01,2023,10,10,Tuesday,Tuesday

In [ ]:
hr.drop(columns=['Weekday'],inplace=True)

In [ ]:
hr

,Emp_ID,Name,Join_Date,Last_Login,Updated_Last_Login,Year,Month,Day,Weekday_Name
0,101,Rahul,2023-01-15,2024-01-10 09:30:00,2024-01-10,2023,1,15,Sunday
1,102,Aman,2023-02-15,2024-02-15 10:15:00,2024-02-15,2023,2,15,Wednesday
2,103,Neha,2023-03-10,2024-03-05 08:45:00,2024-03-05,2023,3,10,Friday
3,104,Priya,2023-04-20,2024-05-25 09:20:00,NaT,2023,4,20,Thursday
4,105,Rohit,2023-06-02,2024-04-20 11:00:00,2024-04-20,2023,6,2,Friday
5,106,Vikas,2023-06-02,2024-05-25 09:20:00,2024-05-25,2023,6,2,Friday
6,107,Anjali,2023-07-15,2024-06-10 08:30:00,2024-06-10,2023,7,15,Saturday
7,108,Karan,2023-08-25,2024-07-15 10:00:00,2024-07-15,2023,8,25,Friday
8,109,Pooja,2023-09-05,2024-08-05 09:45:00,2024-08-05,2023,9,5,Tuesday
9,110,Amit,2023-10-10,2024-09-01 11:15:00,2024-09-01,2023,10,10,Tuesday

In [ ]:
hr['Diff_Days']=hr['Last_Login']-hr['Join_Date']

In [ ]:
hr

,Emp_ID,Name,Join_Date,Last_Login,Updated_Last_Login,Year,Month,Day,Weekday_Name,Diff_Days
0,101,Rahul,2023-01-15,2024-01-10 09:30:00,2024-01-10,2023,1,15,Sunday,360 days 09:30:00
1,102,Aman,2023-02-15,2024-02-15 10:15:00,2024-02-15,2023,2,15,Wednesday,365 days 10:15:00
2,103,Neha,2023-03-10,2024-03-05 08:45:00,2024-03-05,2023,3,10,Friday,361 days 08:45:00
3,104,Priya,2023-04-20,2024-05-25 09:20:00,NaT,2023,4,20,Thursday,401 days 09:20:00
4,105,Rohit,2023-06-02,2024-04-20 11:00:00,2024-04-20,2023,6,2,Friday,323 days 11:00:00
5,106,Vikas,2023-06-02,2024-05-25 09:20:00,2024-05-25,2023,6,2,Friday,358 days 09:20:00
6,107,Anjali,2023-07-15,2024-06-10 08:30:00,2024-06-10,2023,7,15,Saturday,331 days 08:30:00
7,108,Karan,2023-08-25,2024-07-15 10:00:00,2024-07-15,2023,8,25,Friday,325 days 10:00:00
8,109,Pooja,2023-09-05,2024-08-05 09:45:00,2024-08-05,2023,9,5,Tuesday,335 days 09:45:00
9,110,Amit,2023-10-10,2024-09-01 11:15:00,2024-09-01,2023,10,10,Tuesday,327 days 11:15:00

In [ ]:
from dateutil.relativedelta import relativedelta

hr['Experience']=hr.apply(
                        lambda row:(
    f"{relativedelta(row['Last_Login'], row['Join_Date']).years} years "
    f"{relativedelta(row['Last_Login'], row['Join_Date']).months} months "
    f"{relativedelta(row['Last_Login'], row['Join_Date']).days}  days"
    )
    if pd.notnull(row['Last_Login']) and pd.notnull(row['Join_Date']) 
    else
    np.nan,
    axis=1 
)

In [ ]:
hr

,Emp_ID,Name,Join_Date,Last_Login,Updated_Last_Login,Year,Month,Day,Weekday_Name,Diff_Days,Experience
0,101,Rahul,2023-01-15,2024-01-10 09:30:00,2024-01-10,2023,1,15,Sunday,360 days 09:30:00,0 years 11 months 26 days
1,102,Aman,2023-02-15,2024-02-15 10:15:00,2024-02-15,2023,2,15,Wednesday,365 days 10:15:00,1 years 0 months 0 days
2,103,Neha,2023-03-10,2024-03-05 08:45:00,2024-03-05,2023,3,10,Friday,361 days 08:45:00,0 years 11 months 24 days
3,104,Priya,2023-04-20,2024-05-25 09:20:00,NaT,2023,4,20,Thursday,401 days 09:20:00,1 years 1 months 5 days
4,105,Rohit,2023-06-02,2024-04-20 11:00:00,2024-04-20,2023,6,2,Friday,323 days 11:00:00,0 years 10 months 18 days
5,106,Vikas,2023-06-02,2024-05-25 09:20:00,2024-05-25,2023,6,2,Friday,358 days 09:20:00,0 years 11 months 23 days
6,107,Anjali,2023-07-15,2024-06-10 08:30:00,2024-06-10,2023,7,15,Saturday,331 days 08:30:00,0 years 10 months 26 days
7,108,Karan,2023-08-25,2024-07-15 10:00:00,2024-07-15,2023,8,25,Friday,325 days 10:00:00,0 years 10 months 20 days
8,109,Pooja,2023-09-05,2024-08-05 09:45:00,2024-08-05,2023,9,5,Tuesday,335 days 09:45:00,0 years 11 months 0 days
9,110,Amit,2023-10-10,2024-09-01 11:15:00,2024-09-01,2023,10,10,Tuesday,327 days 11:15:00,0 years 10 months 22 days

In [ ]:
telecome

,Customer_ID,Customer_Name,Signup_Date,Last_Login_Date,Subscription_End,Monthly_Charges,Churn
0,1001,Rahul,2022-01-15,2024-01-10,2024-12-31,499,0
1,1002,Aman,15/03/2022,2024-02-15,2024-11-30,699,1
2,1003,Neha,"Apr 10, 2022",2024-03-05,2024-10-15,899,0
3,1004,Priya,2022/05/20,NaN,2024-09-20,599,1
4,1005,Rohit,NaN,2024-04-20,2024-08-31,799,0
5,1006,Vikas,2022-06-31,2024-05-25,NaN,999,1
6,1007,Anjali,07-25-2022,2024-06-10,2024-07-31,549,0
7,1008,Karan,2022-08-15,2024-07-15,2024-06-30,649,1
8,1009,Pooja,"September 5, 2022",2024-08-05,2024-05-31,749,0
9,1010,Amit,2022.10.10,2024-09-01,2024-04-30,899,1

In [ ]:
date_cols=['Signup_Date','Last_Login_Date','Subscription_End']
for i in date_cols:
    # telecome[i]=pd.to_datetime(telecome[i],errors='coerce',format="mixed")
    telecome[i]=telecome[i].fillna(telecome[i].median())

In [ ]:
telecome

,Customer_ID,Customer_Name,Signup_Date,Last_Login_Date,Subscription_End,Monthly_Charges,Churn
0,1001,Rahul,2022-01-15,2024-01-10,2024-12-31,499,0
1,1002,Aman,2022-03-15,2024-02-15,2024-11-30,699,1
2,1003,Neha,2022-04-10,2024-03-05,2024-10-15,899,0
3,1004,Priya,2022-05-20,2024-05-25,2024-09-20,599,1
4,1005,Rohit,2022-06-22,2024-04-20,2024-08-31,799,0
5,1006,Vikas,2022-06-22,2024-05-25,2024-08-31,999,1
6,1007,Anjali,2022-07-25,2024-06-10,2024-07-31,549,0
7,1008,Karan,2022-08-15,2024-07-15,2024-06-30,649,1
8,1009,Pooja,2022-09-05,2024-08-05,2024-05-31,749,0
9,1010,Amit,2022-10-10,2024-09-01,2024-04-30,899,1

In [ ]:
telecome.rename(columns={
    'Signup_Date':'Registration_Date',
    'Last_Login_Date':'Last_Login_Date',
    'Subscription_End':'Subscription_End'
})

,Customer_ID,Customer_Name,Registration_Date,Last_Login_Date,Subscription_End,Monthly_Charges,Churn
0,1001,Rahul,2022-01-15,2024-01-10,2024-12-31,499,0
1,1002,Aman,2022-03-15,2024-02-15,2024-11-30,699,1
2,1003,Neha,2022-04-10,2024-03-05,2024-10-15,899,0
3,1004,Priya,2022-05-20,2024-05-25,2024-09-20,599,1
4,1005,Rohit,2022-06-22,2024-04-20,2024-08-31,799,0
5,1006,Vikas,2022-06-22,2024-05-25,2024-08-31,999,1
6,1007,Anjali,2022-07-25,2024-06-10,2024-07-31,549,0
7,1008,Karan,2022-08-15,2024-07-15,2024-06-30,649,1
8,1009,Pooja,2022-09-05,2024-08-05,2024-05-31,749,0
9,1010,Amit,2022-10-10,2024-09-01,2024-04-30,899,1

Module 9: Sorting & Ranking
sort_values()
sort_index()
rank()
nlargest()
nsmallest()

Module 10: Aggregation & Statistics
sum()
mean()
median()
mode()
max()
min()
count()
std()
var()
corr()

Module 11: GroupBy (Very Important)
groupby()

Single Aggregation
Multiple Aggregations
Custom Aggregations
GroupBy + Filter

In [ ]:
Module 9: Sorting & Ranking
sort_values()
sort_index()
rank()
nlargest()
nsmallest()

In [ ]:
name marks  rank
a       50   2
b       52      1
c       50      2

In [ ]:
import pandas as pd
data={
    'EMP_iD':[101,102,103,104,105],
    'Name':['Rahul','Aman','Neha','Priya','Rohit'],
    'Department':['IT','HR','Finance','IT','HR'],
    'Salary':[50000,60000,55000,80000,70000],
    'performance':[80,90,70,95,85]


}

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df

   EMP_iD   Name Department  Salary  performance
0     101  Rahul         IT   50000           80
1     102   Aman         HR   60000           90
2     103   Neha    Finance   55000           70
3     104  Priya         IT   80000           95
4     105  Rohit         HR   70000           85

In [ ]:
df.sort_values(by='Salary',ascending=False)

   EMP_iD   Name Department  Salary  performance
3     104  Priya         IT   80000           95
4     105  Rohit         HR   70000           85
1     102   Aman         HR   60000           90
2     103   Neha    Finance   55000           70
0     101  Rahul         IT   50000           80

In [ ]:
df

   EMP_iD   Name Department  Salary  performance
0     101  Rahul         IT   50000           80
1     102   Aman         HR   60000           90
2     103   Neha    Finance   55000           70
3     104  Priya         IT   80000           95
4     105  Rohit         HR   70000           85

In [ ]:
df.sort_values(by='EMP_iD',ascending=False)

   EMP_iD   Name Department  Salary  performance
4     105  Rohit         HR   70000           85
3     104  Priya         IT   80000           95
2     103   Neha    Finance   55000           70
1     102   Aman         HR   60000           90
0     101  Rahul         IT   50000           80

In [ ]:
df.sort_values(by=['Department','Salary'],ascending=True)

   EMP_iD   Name Department  Salary  performance
2     103   Neha    Finance   55000           70
1     102   Aman         HR   60000           90
4     105  Rohit         HR   70000           85
0     101  Rahul         IT   50000           80
3     104  Priya         IT   80000           95

In [ ]:
df.sort_index()

   EMP_iD   Name Department  Salary  performance
0     101  Rahul         IT   50000           80
1     102   Aman         HR   60000           90
2     103   Neha    Finance   55000           70
3     104  Priya         IT   80000           95
4     105  Rohit         HR   70000           85

In [ ]:
df2=df.sort_values(by='EMP_iD',ascending=False)

In [ ]:
df2

   EMP_iD   Name Department  Salary  performance
4     105  Rohit         HR   70000           85
3     104  Priya         IT   80000           95
2     103   Neha    Finance   55000           70
1     102   Aman         HR   60000           90
0     101  Rahul         IT   50000           80

In [ ]:
df['Salary_Rank']=df['Salary'].rank()

In [ ]:
df

   EMP_iD   Name Department  Salary  performance  Salary_Rank
0     101  Rahul         IT   50000           80          1.0
1     102   Aman         HR   60000           90          3.0
2     103   Neha    Finance   55000           70          2.0
3     104  Priya         IT   80000           95          5.0
4     105  Rohit         HR   70000           85          4.0

In [ ]:
print(df[['Name','Salary','Salary_Rank']])

    Name  Salary  Salary_Rank
0  Rahul   50000          1.0
1   Aman   60000          3.0
2   Neha   55000          2.0
3  Priya   80000          5.0
4  Rohit   70000          4.0

In [ ]:
df['Salary_Rank']=df['Salary'].rank(ascending=False)

In [ ]:
import pandas as pd
data={
    'EMP_iD':[101,102,103,104,105],
    'Name':['Rahul','Aman','Neha','Priya','Rohit'],
    'Department':['IT','HR','Finance','IT','HR'],
    'Salary':[50000,60000,55000,80000,70000],
    'performance':[80,90,70,95,85]


}
df['Salary_Rank']=df['Salary'].rank(ascending=False,method='dense')
print(df[['Name','Salary','Salary_Rank']])

    Name  Salary  Salary_Rank
0  Rahul   50000          5.0
1   Aman   60000          3.0
2   Neha   55000          4.0
3  Priya   80000          1.0
4  Rohit   70000          2.0

In [ ]:
df

   EMP_iD   Name Department  Salary  performance  Salary_Rank
0     101  Rahul         IT   50000           80          5.0
1     102   Aman         HR   60000           90          3.0
2     103   Neha    Finance   55000           70          4.0
3     104  Priya         IT   80000           95          1.0
4     105  Rohit         HR   70000           85          2.0

In [ ]:
df.nlargest(1,'Salary')

   EMP_iD   Name Department  Salary  performance  Salary_Rank
3     104  Priya         IT   80000           95          1.0

In [ ]:
print(df[df['Salary_Rank']==1][['Name','Salary','Salary_Rank']])

    Name  Salary  Salary_Rank
3  Priya   80000          1.0

In [ ]:
df.nsmallest(3,'Salary')

   EMP_iD   Name Department  Salary  performance  Salary_Rank
0     101  Rahul         IT   50000           80          5.0
2     103   Neha    Finance   55000           70          4.0
1     102   Aman         HR   60000           90          3.0

In [ ]:
df.describe()

           EMP_iD        Salary  performance  Salary_Rank
count    5.000000      5.000000     5.000000     5.000000
mean   103.000000  63000.000000    84.000000     3.000000
std      1.581139  12041.594579     9.617692     1.581139
min    101.000000  50000.000000    70.000000     1.000000
25%    102.000000  55000.000000    80.000000     2.000000
50%    103.000000  60000.000000    85.000000     3.000000
75%    104.000000  70000.000000    90.000000     4.000000
max    105.000000  80000.000000    95.000000     5.000000

In [ ]:
distributed_salary=df['Salary'].sum()

In [ ]:
print("Total Salary Distributed:",distributed_salary)

Total Salary Distributed: 315000

In [ ]:
df['Salary'].mean()

np.float64(63000.0)

In [ ]:
df['Department'].mode()[0]

'HR'

In [ ]:
df.groupby('Department')['Salary'].sum()

Department
Finance     55000
HR         130000
IT         130000
Name: Salary, dtype: int64

In [ ]:
df.groupby('Department')['Salary'].mean()

Department
Finance    55000.0
HR         65000.0
IT         65000.0
Name: Salary, dtype: float64

In [ ]:
df

   EMP_iD   Name Department  Salary  performance  Salary_Rank
0     101  Rahul         IT   50000           80          5.0
1     102   Aman         HR   60000           90          3.0
2     103   Neha    Finance   55000           70          4.0
3     104  Priya         IT   80000           95          1.0
4     105  Rohit         HR   70000           85          2.0

In [ ]:
df.groupby('Department')['Salary'].mean()

Department
Finance    55000.0
HR         65000.0
IT         65000.0
Name: Salary, dtype: float64

In [ ]:
df.groupby('Department')['Salary'].agg(
    ['sum','mean','max','min']
)

               sum     mean    max    min
Department
Finance      55000  55000.0  55000  55000
HR          130000  65000.0  70000  60000
IT          130000  65000.0  80000  50000

In [ ]:
DEPT HIGHEST   LOWEST   DIFF
IT      50000   40000       10000

In [ ]:
df.groupby('Department')['Salary'].agg(
    lambda x: x.max() - x.min()


)

Department
Finance        0
HR         10000
IT         30000
Name: Salary, dtype: int64

In [ ]:
df.groupby('Department')['Salary'].agg([
    "max",
    "min",
    lambda x: x.max() - x.min()
])

              max    min  <lambda_0>
Department
Finance     55000  55000           0
HR          70000  60000       10000
IT          80000  50000       30000

In [ ]:
# GroupBy + Filter
df

   EMP_iD   Name Department  Salary  performance  Salary_Rank
0     101  Rahul         IT   50000           80          5.0
1     102   Aman         HR   60000           90          3.0
2     103   Neha    Finance   55000           70          4.0
3     104  Priya         IT   80000           95          1.0
4     105  Rohit         HR   70000           85          2.0

In [ ]:
df.groupby('Department').filter(lambda x: x['Salary'].mean()>60000)

   EMP_iD   Name Department  Salary  performance  Salary_Rank
0     101  Rahul         IT   50000           80          5.0
1     102   Aman         HR   60000           90          3.0
3     104  Priya         IT   80000           95          1.0
4     105  Rohit         HR   70000           85          2.0

In [ ]:
df.groupby('Department')['Salary'].mean()

Department
Finance    55000.0
HR         65000.0
IT         65000.0
Name: Salary, dtype: float64

In [ ]:
df

   EMP_iD   Name Department  Salary  performance  Salary_Rank
0     101  Rahul         IT   50000           80          5.0
1     102   Aman         HR   60000           90          3.0
2     103   Neha    Finance   55000           70          4.0
3     104  Priya         IT   80000           95          1.0
4     105  Rohit         HR   70000           85          2.0

In [ ]:
Find Out:-
1. Who is Top 20% Earner in Each Department or Company.
2. Which Department is more expensive
3. Which Department has more Employees
4. Which Department is more productive
5. List the top 2 highest earners in each department with their names

    Name  performance
3  Priya           95

In [ ]:
top_performers = df.loc[df.groupby('Department')['performance'].idxmax()]

print(top_performers[['Department', 'Name', 'performance']])

  Department   Name  performance
2    Finance   Neha           70
1         HR   Aman           90
3         IT  Priya           95

In [ ]:
top_20 = (
    df.groupby('Department', group_keys=False)
      .apply(lambda x: x.nlargest(max(1, int(len(x)*0.2)), 'Salary'))
)

C:\Users\Vishnu\AppData\Local\Temp\ipykernel_12148\371898019.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.nlargest(max(1, int(len(x)*0.2)), 'Salary'))

In [ ]:
top_20

   EMP_iD   Name Department  Salary  performance  Salary_Rank
2     103   Neha    Finance   55000           70          4.0
4     105  Rohit         HR   70000           85          2.0
3     104  Priya         IT   80000           95          1.0

In [ ]:
top_20 = df.nlargest(int(len(df) * 0.2), 'Salary')
print(top_20[['Name', 'Department', 'Salary']])

    Name Department  Salary
3  Priya         IT   80000

In [ ]:
dept_expensive=df.groupby('Department')['Salary'].sum()

In [ ]:
dept_expensive.idxmax()

'HR'

In [ ]:
dept_employees = df.groupby('Department')['EMP_iD'].count()

In [ ]:
dept_employees.idxmax()

'HR'

In [ ]:
top2=df.groupby(
    'Department', group_keys=False).apply(lambda x: x.nlargest(1, 'Salary')
                                    
)

print(top2[['Department','Name','Salary']])

  Department   Name  Salary
2    Finance   Neha   55000
4         HR  Rohit   70000
3         IT  Priya   80000

C:\Users\Vishnu\AppData\Local\Temp\ipykernel_12148\684793376.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  'Department', group_keys=False).apply(lambda x: x.nlargest(1, 'Salary')

In [ ]:
df

   EMP_iD   Name Department  Salary  performance  Salary_Rank
0     101  Rahul         IT   50000           80          5.0
1     102   Aman         HR   60000           90          3.0
2     103   Neha    Finance   55000           70          4.0
3     104  Priya         IT   80000           95          1.0
4     105  Rohit         HR   70000           85          2.0

Module 12: Reshaping Data
Pivot Table
Crosstab
Melt
Stack
Unstack

Module 13: Combining Data
concat()
merge()
Inner Join
Left Join
Right Join
Outer Join
join()

Module 14: Feature Engineering for ML
Creating Features
Binning (cut)
Quantile Binning (qcut)
Encoding Categories
Dummy Variables (get_dummies)
Label Encoding Preparation

In [ ]:
import pandas as pd

customers = pd.DataFrame({
    "Customer_ID":[101,102,103,104,105,106],
    "Customer_Name":[
        "Rahul",
        "Aman",
        "Neha",
        "Priya",
        "Rohit",
        "Anjali"
    ],
    "City":[
        "Delhi",
        "Mumbai",
        "Delhi",
        "Pune",
        "Bangalore",
        "Mumbai"
    ],
    "Gender":[
        "Male",
        "Male",
        "Female",
        "Female",
        "Male",
        "Female"
    ],
    "Age":[
        22,
        35,
        28,
        42,
        31,
        25
    ]
})

customers

   Customer_ID Customer_Name       City  Gender  Age
0          101         Rahul      Delhi    Male   22
1          102          Aman     Mumbai    Male   35
2          103          Neha      Delhi  Female   28
3          104         Priya       Pune  Female   42
4          105         Rohit  Bangalore    Male   31
5          106        Anjali     Mumbai  Female   25

In [ ]:
products = pd.DataFrame({
    "Product_ID":[
        1,2,3,4,5
    ],
    "Product_Name":[
        "Laptop",
        "Mobile",
        "Headphones",
        "Keyboard",
        "Monitor"
    ],
    "Category":[
        "Electronics",
        "Electronics",
        "Accessories",
        "Accessories",
        "Electronics"
    ]
})

products

   Product_ID Product_Name     Category
0           1       Laptop  Electronics
1           2       Mobile  Electronics
2           3   Headphones  Accessories
3           4     Keyboard  Accessories
4           5      Monitor  Electronics

In [ ]:
orders = pd.DataFrame({
    "Order_ID":[
        1001,1002,1003,1004,1005,
        1006,1007,1008,1009,1010
    ],

    "Customer_ID":[
        101,102,101,103,104,
        105,106,102,103,101
    ],

    "Product_ID":[
        1,2,3,2,5,
        1,4,5,3,2
    ],

    "Quantity":[
        1,2,1,3,1,
        1,2,1,2,4
    ],

    "Amount":[
        60000,
        40000,
        2500,
        60000,
        20000,
        65000,
        4000,
        18000,
        5000,
        80000
    ]
})

orders

   Order_ID  Customer_ID  Product_ID  Quantity  Amount
0      1001          101           1         1   60000
1      1002          102           2         2   40000
2      1003          101           3         1    2500
3      1004          103           2         3   60000
4      1005          104           5         1   20000
5      1006          105           1         1   65000
6      1007          106           4         2    4000
7      1008          102           5         1   18000
8      1009          103           3         2    5000
9      1010          101           2         4   80000

In [ ]:
df=pd.pivot_table(orders,index='Customer_ID',values='Amount',aggfunc='sum')

In [ ]:
df

             Amount
Customer_ID
101          142500
102           58000
103           65000
104           20000
105           65000
106            4000

In [ ]:
# Cross Tab
pd.crosstab(customers['City'],customers['Gender'])

Gender     Female  Male
City
Bangalore       0     1
Delhi           1     1
Mumbai          1     1
Pune            1     0

In [ ]:
customers

   Customer_ID Customer_Name       City  Gender  Age
0          101         Rahul      Delhi    Male   22
1          102          Aman     Mumbai    Male   35
2          103          Neha      Delhi  Female   28
3          104         Priya       Pune  Female   42
4          105         Rohit  Bangalore    Male   31
5          106        Anjali     Mumbai  Female   25

In [ ]:
# melt
pd.melt(customers,id_vars=['Customer_ID','Customer_Name'],value_vars=['City','Gender','Age'])

    Customer_ID Customer_Name variable      value
0           101         Rahul     City      Delhi
1           102          Aman     City     Mumbai
2           103          Neha     City      Delhi
3           104         Priya     City       Pune
4           105         Rohit     City  Bangalore
5           106        Anjali     City     Mumbai
6           101         Rahul   Gender       Male
7           102          Aman   Gender       Male
8           103          Neha   Gender     Female
9           104         Priya   Gender     Female
10          105         Rohit   Gender       Male
11          106        Anjali   Gender     Female
12          101         Rahul      Age         22
13          102          Aman      Age         35
14          103          Neha      Age         28
15          104         Priya      Age         42
16          105         Rohit      Age         31
17          106        Anjali      Age         25

In [ ]:
stacked=customers.stack()

In [ ]:
stacked

0  Customer_ID            101
   Customer_Name        Rahul
   City                 Delhi
   Gender                Male
   Age                     22
1  Customer_ID            102
   Customer_Name         Aman
   City                Mumbai
   Gender                Male
   Age                     35
2  Customer_ID            103
   Customer_Name         Neha
   City                 Delhi
   Gender              Female
   Age                     28
3  Customer_ID            104
   Customer_Name        Priya
   City                  Pune
   Gender              Female
   Age                     42
4  Customer_ID            105
   Customer_Name        Rohit
   City             Bangalore
   Gender                Male
   Age                     31
5  Customer_ID            106
   Customer_Name       Anjali
   City                Mumbai
   Gender              Female
   Age                     25
dtype: object

In [ ]:
customers

   Customer_ID Customer_Name       City  Gender  Age
0          101         Rahul      Delhi    Male   22
1          102          Aman     Mumbai    Male   35
2          103          Neha      Delhi  Female   28
3          104         Priya       Pune  Female   42
4          105         Rohit  Bangalore    Male   31
5          106        Anjali     Mumbai  Female   25

In [ ]:
stacked.unstack()

  Customer_ID Customer_Name       City  Gender Age
0         101         Rahul      Delhi    Male  22
1         102          Aman     Mumbai    Male  35
2         103          Neha      Delhi  Female  28
3         104         Priya       Pune  Female  42
4         105         Rohit  Bangalore    Male  31
5         106        Anjali     Mumbai  Female  25

In [ ]:
customers

   Customer_ID Customer_Name       City  Gender  Age
0          101         Rahul      Delhi    Male   22
1          102          Aman     Mumbai    Male   35
2          103          Neha      Delhi  Female   28
3          104         Priya       Pune  Female   42
4          105         Rohit  Bangalore    Male   31
5          106        Anjali     Mumbai  Female   25

In [ ]:
Customer ID     101
Customer _Name   Rahul
City            Delhi
Gender          male
Age             22

Customer ID     102
Customer _Name   Aman
City            Mumbai
Gender           35

In [ ]:
stacked=customers.stack()

In [ ]:
stacked

0  Customer_ID            101
   Customer_Name        Rahul
   City                 Delhi
   Gender                Male
   Age                     22
1  Customer_ID            102
   Customer_Name         Aman
   City                Mumbai
   Gender                Male
   Age                     35
2  Customer_ID            103
   Customer_Name         Neha
   City                 Delhi
   Gender              Female
   Age                     28
3  Customer_ID            104
   Customer_Name        Priya
   City                  Pune
   Gender              Female
   Age                     42
4  Customer_ID            105
   Customer_Name        Rohit
   City             Bangalore
   Gender                Male
   Age                     31
5  Customer_ID            106
   Customer_Name       Anjali
   City                Mumbai
   Gender              Female
   Age                     25
dtype: object

In [ ]:
stacked.unstack()

  Customer_ID Customer_Name       City  Gender Age
0         101         Rahul      Delhi    Male  22
1         102          Aman     Mumbai    Male  35
2         103          Neha      Delhi  Female  28
3         104         Priya       Pune  Female  42
4         105         Rohit  Bangalore    Male  31
5         106        Anjali     Mumbai  Female  25

In [ ]:
Module 13: Combining Data
concat()
merge()
Inner Join
Left Join
Right Join
Outer Join
join()

In [ ]:
customers

   Customer_ID Customer_Name       City  Gender  Age
0          101         Rahul      Delhi    Male   22
1          102          Aman     Mumbai    Male   35
2          103          Neha      Delhi  Female   28
3          104         Priya       Pune  Female   42
4          105         Rohit  Bangalore    Male   31
5          106        Anjali     Mumbai  Female   25

In [ ]:
products

   Product_ID Product_Name     Category
0           1       Laptop  Electronics
1           2       Mobile  Electronics
2           3   Headphones  Accessories
3           4     Keyboard  Accessories
4           5      Monitor  Electronics

In [ ]:
orders

   Order_ID  Customer_ID  Product_ID  Quantity  Amount
0      1001          101           1         1   60000
1      1002          102           2         2   40000
2      1003          101           3         1    2500
3      1004          103           2         3   60000
4      1005          104           5         1   20000
5      1006          105           1         1   65000
6      1007          106           4         2    4000
7      1008          102           5         1   18000
8      1009          103           3         2    5000
9      1010          101           2         4   80000

In [ ]:
combined_data=orders.merge(customers,on='Customer_ID').merge(products,on='Product_ID')

In [ ]:
combined_data

,Order_ID,Customer_ID,Product_ID,Quantity,Amount,Customer_Name,City,Gender,Age,Product_Name,Category
0,1001,101,1,1,60000,Rahul,Delhi,Male,22,Laptop,Electronics
1,1002,102,2,2,40000,Aman,Mumbai,Male,35,Mobile,Electronics
2,1003,101,3,1,2500,Rahul,Delhi,Male,22,Headphones,Accessories
3,1004,103,2,3,60000,Neha,Delhi,Female,28,Mobile,Electronics
4,1005,104,5,1,20000,Priya,Pune,Female,42,Monitor,Electronics
5,1006,105,1,1,65000,Rohit,Bangalore,Male,31,Laptop,Electronics
6,1007,106,4,2,4000,Anjali,Mumbai,Female,25,Keyboard,Accessories
7,1008,102,5,1,18000,Aman,Mumbai,Male,35,Monitor,Electronics
8,1009,103,3,2,5000,Neha,Delhi,Female,28,Headphones,Accessories
9,1010,101,2,4,80000,Rahul,Delhi,Male,22,Mobile,Electronics

In [ ]:
pd.merge(orders,customers,on='Customer_ID',how='inner')

,Order_ID,Customer_ID,Product_ID,Quantity,Amount,Customer_Name,City,Gender,Age
0,1001,101,1,1,60000,Rahul,Delhi,Male,22
1,1002,102,2,2,40000,Aman,Mumbai,Male,35
2,1003,101,3,1,2500,Rahul,Delhi,Male,22
3,1004,103,2,3,60000,Neha,Delhi,Female,28
4,1005,104,5,1,20000,Priya,Pune,Female,42
5,1006,105,1,1,65000,Rohit,Bangalore,Male,31
6,1007,106,4,2,4000,Anjali,Mumbai,Female,25
7,1008,102,5,1,18000,Aman,Mumbai,Male,35
8,1009,103,3,2,5000,Neha,Delhi,Female,28
9,1010,101,2,4,80000,Rahul,Delhi,Male,22

In [ ]:
pd.merge(customers,orders,on='Customer_ID',how='inner')

,Customer_ID,Customer_Name,City,Gender,Age,Order_ID,Product_ID,Quantity,Amount
0,101,Rahul,Delhi,Male,22,1001,1,1,60000
1,101,Rahul,Delhi,Male,22,1003,3,1,2500
2,101,Rahul,Delhi,Male,22,1010,2,4,80000
3,102,Aman,Mumbai,Male,35,1002,2,2,40000
4,102,Aman,Mumbai,Male,35,1008,5,1,18000
5,103,Neha,Delhi,Female,28,1004,2,3,60000
6,103,Neha,Delhi,Female,28,1009,3,2,5000
7,104,Priya,Pune,Female,42,1005,5,1,20000
8,105,Rohit,Bangalore,Male,31,1006,1,1,65000
9,106,Anjali,Mumbai,Female,25,1007,4,2,4000

In [ ]:
orders

   Order_ID  Customer_ID  Product_ID  Quantity  Amount
0      1001          101           1         1   60000
1      1002          102           2         2   40000
2      1003          101           3         1    2500
3      1004          103           2         3   60000
4      1005          104           5         1   20000
5      1006          105           1         1   65000
6      1007          106           4         2    4000
7      1008          102           5         1   18000
8      1009          103           3         2    5000
9      1010          101           2         4   80000

In [ ]:
customers

   Customer_ID Customer_Name       City  Gender  Age
0          101         Rahul      Delhi    Male   22
1          102          Aman     Mumbai    Male   35
2          103          Neha      Delhi  Female   28
3          104         Priya       Pune  Female   42
4          105         Rohit  Bangalore    Male   31
5          106        Anjali     Mumbai  Female   25

In [ ]:
pd.merge(customers,orders,on='Customer_ID',how='right')

,Customer_ID,Customer_Name,City,Gender,Age,Order_ID,Product_ID,Quantity,Amount
0,101,Rahul,Delhi,Male,22,1001,1,1,60000
1,102,Aman,Mumbai,Male,35,1002,2,2,40000
2,101,Rahul,Delhi,Male,22,1003,3,1,2500
3,103,Neha,Delhi,Female,28,1004,2,3,60000
4,104,Priya,Pune,Female,42,1005,5,1,20000
5,105,Rohit,Bangalore,Male,31,1006,1,1,65000
6,106,Anjali,Mumbai,Female,25,1007,4,2,4000
7,102,Aman,Mumbai,Male,35,1008,5,1,18000
8,103,Neha,Delhi,Female,28,1009,3,2,5000
9,101,Rahul,Delhi,Male,22,1010,2,4,80000

In [ ]:
pd.merge(customers,orders,on='Customer_ID',how='left')

,Customer_ID,Customer_Name,City,Gender,Age,Order_ID,Product_ID,Quantity,Amount
0,101,Rahul,Delhi,Male,22,1001,1,1,60000
1,101,Rahul,Delhi,Male,22,1003,3,1,2500
2,101,Rahul,Delhi,Male,22,1010,2,4,80000
3,102,Aman,Mumbai,Male,35,1002,2,2,40000
4,102,Aman,Mumbai,Male,35,1008,5,1,18000
5,103,Neha,Delhi,Female,28,1004,2,3,60000
6,103,Neha,Delhi,Female,28,1009,3,2,5000
7,104,Priya,Pune,Female,42,1005,5,1,20000
8,105,Rohit,Bangalore,Male,31,1006,1,1,65000
9,106,Anjali,Mumbai,Female,25,1007,4,2,4000

In [ ]:
employee=pd.DataFrame({
    "Emp_ID":[101,102,103,104],
    "Name":[
        "Rahul",
        "Aman",
        "Neha",
        "Priya"
    ]})

In [ ]:
employee

   Emp_ID   Name
0     101  Rahul
1     102   Aman
2     103   Neha
3     104  Priya

In [ ]:
salary=pd.DataFrame({
    "Emp_ID":[101,107,108,103],
            'Salary':[50000,60000,55000,70000]})

In [ ]:
salary

   Emp_ID  Salary
0     101   50000
1     107   60000
2     108   55000
3     103   70000

In [ ]:
pd.merge(employee,salary,on='Emp_ID',how='inner')

   Emp_ID   Name  Salary
0     101  Rahul   50000
1     103   Neha   70000

In [ ]:
pd.merge(employee,salary,on='Emp_ID',how='left')

   Emp_ID   Name   Salary
0     101  Rahul  50000.0
1     102   Aman      NaN
2     103   Neha  70000.0
3     104  Priya      NaN

In [ ]:
pd.merge(employee,salary,on='Emp_ID',how='right')

   Emp_ID   Name  Salary
0     101  Rahul   50000
1     107    NaN   60000
2     108    NaN   55000
3     103   Neha   70000

In [ ]:
df1 = pd.DataFrame({'ID': [1, 2, 3, 4, 5],
                     'Name': ['Abhinav', 'John', 'Alice', 'Bob', 'Charlie'],
                     'department': ['IT', 'HR', 'Finance', 'Marketing', 'Sales']})
df2 = pd.DataFrame({'ID': [1, 2, 3 ,6, 7], 
                    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
                    'Salary': [50000, 60000, 55000, 58000, 62000]})

merged_df = pd.merge(df1, df2, on='ID', how='inner') 
print(merged_df)

   ID     Name department         City  Salary
0   1  Abhinav         IT     New York   50000
1   2     John         HR  Los Angeles   60000
2   3    Alice    Finance      Chicago   55000

In [ ]:
pd.merge(employee,salary,on='Emp_ID',how='outer')

   Emp_ID   Name   Salary
0     101  Rahul  50000.0
1     102   Aman      NaN
2     103   Neha  70000.0
3     104  Priya      NaN
4     107    NaN  60000.0
5     108    NaN  55000.0

Module 14: Feature Engineering for ML
Creating Features
Binning (cut)
Quantile Binning (qcut)
Encoding Categories
Dummy Variables (get_dummies)
Label Encoding Preparation

In [ ]:
orders

   Order_ID  Customer_ID  Product_ID  Quantity  Amount
0      1001          101           1         1   60000
1      1002          102           2         2   40000
2      1003          101           3         1    2500
3      1004          103           2         3   60000
4      1005          104           5         1   20000
5      1006          105           1         1   65000
6      1007          106           4         2    4000
7      1008          102           5         1   18000
8      1009          103           3         2    5000
9      1010          101           2         4   80000

In [ ]:
orders['Avg_Order-Value']=orders['Amount']/orders['Quantity']

In [ ]:
orders

   Order_ID  Customer_ID  Product_ID  Quantity  Amount  Avg_Order-Value
0      1001          101           1         1   60000          60000.0
1      1002          102           2         2   40000          20000.0
2      1003          101           3         1    2500           2500.0
3      1004          103           2         3   60000          20000.0
4      1005          104           5         1   20000          20000.0
5      1006          105           1         1   65000          65000.0
6      1007          106           4         2    4000           2000.0
7      1008          102           5         1   18000          18000.0
8      1009          103           3         2    5000           2500.0
9      1010          101           2         4   80000          20000.0

In [ ]:
customers

   Customer_ID Customer_Name       City  Gender  Age
0          101         Rahul      Delhi    Male   22
1          102          Aman     Mumbai    Male   35
2          103          Neha      Delhi  Female   28
3          104         Priya       Pune  Female   42
4          105         Rohit  Bangalore    Male   31
5          106        Anjali     Mumbai  Female   25

In [ ]:
customers['Age_Group'] = pd.cut(customers['Age'], bins=[0,10,15,25,45], labels=['Child','Youth','Adult','Senior'])

In [ ]:
customers

   Customer_ID Customer_Name       City  Gender  Age Age_Group
0          101         Rahul      Delhi    Male   22     Adult
1          102          Aman     Mumbai    Male   35    Senior
2          103          Neha      Delhi  Female   28    Senior
3          104         Priya       Pune  Female   42    Senior
4          105         Rohit  Bangalore    Male   31    Senior
5          106        Anjali     Mumbai  Female   25     Adult

In [ ]:
orders

   Order_ID  Customer_ID  Product_ID  Quantity  Amount  Avg_Order-Value
0      1001          101           1         1   60000          60000.0
1      1002          102           2         2   40000          20000.0
2      1003          101           3         1    2500           2500.0
3      1004          103           2         3   60000          20000.0
4      1005          104           5         1   20000          20000.0
5      1006          105           1         1   65000          65000.0
6      1007          106           4         2    4000           2000.0
7      1008          102           5         1   18000          18000.0
8      1009          103           3         2    5000           2500.0
9      1010          101           2         4   80000          20000.0

In [ ]:
orders['Amount_Group'] = pd.qcut(orders['Amount'], q=4, labels=['Low', 'Medium', 'High', 'Very High'])

In [ ]:
orders

,Order_ID,Customer_ID,Product_ID,Quantity,Amount,Avg_Order-Value,Amount_Group
0,1001,101,1,1,60000,60000.0,High
1,1002,102,2,2,40000,20000.0,High
2,1003,101,3,1,2500,2500.0,Low
3,1004,103,2,3,60000,20000.0,High
4,1005,104,5,1,20000,20000.0,Medium
5,1006,105,1,1,65000,65000.0,Very High
6,1007,106,4,2,4000,2000.0,Low
7,1008,102,5,1,18000,18000.0,Medium
8,1009,103,3,2,5000,2500.0,Low
9,1010,101,2,4,80000,20000.0,Very High

In [ ]:
df=pd.DataFrame({
    'Age':[18,22,27,35,42,25,30,40,45,60,65]
})

In [ ]:
df

    Age
0    18
1    22
2    27
3    35
4    42
5    25
6    30
7    40
8    45
9    60
10   65

In [ ]:
df['Age_Group']=pd.cut(df['Age'],bins=[0,18,])

In [ ]:
df

    Age        Age_Group
0    18  (17.953, 29.75]
1    22  (17.953, 29.75]
2    27  (17.953, 29.75]
3    35    (29.75, 41.5]
4    42    (41.5, 53.25]
5    25  (17.953, 29.75]
6    30    (29.75, 41.5]
7    40    (29.75, 41.5]
8    45    (41.5, 53.25]
9    60    (53.25, 65.0]
10   65    (53.25, 65.0]

In [ ]:
total range
65-18=47
47-18=29
29-18=11
47/3=15.67

In [ ]:
pd.cut(customers['Age'],bins=[0,18,35,60,100],labels=['Child','Youth','Adult','Senior'])

In [ ]:
import pandas as pd
df=pd.read_csv('C:\\Users\\Vishnu\\Desktop\\Python_Evening\\loan_data.csv')

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df['ApplicantIncome'].max()

np.int64(81000)

In [ ]:
df['Applicant Income Group']=pd.qcut(df['ApplicantIncome'],q=4,labels=['Low Income','Lower Middle Income','Upper Middle Income','High Income'])

In [ ]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Applicant Income Group
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,High Income
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,Upper Middle Income
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,Lower Middle Income
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,Low Income
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,High Income
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,Lower Middle Income
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,Upper Middle Income
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y,High Income
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y,High Income
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,Upper Middle Income

In [ ]:
df[df['ApplicantIncome']==81000]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Applicant Income Group
409,LP002317,Male,Yes,3+,Graduate,No,81000,0.0,360.0,360.0,0.0,Rural,N,High Income

In [ ]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Applicant Income Group
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,High Income
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,Upper Middle Income
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,Lower Middle Income
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,Low Income
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,High Income

In [ ]:
df['Applicant Income']=pd.qcut(df['ApplicantIncome'],q=4)

In [ ]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Applicant Income Group,Applicant Income
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,High Income,"(5795.0, 81000.0]"
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,Upper Middle Income,"(3812.5, 5795.0]"
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,Lower Middle Income,"(2877.5, 3812.5]"
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,Low Income,"(149.999, 2877.5]"
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,High Income,"(5795.0, 81000.0]"

In [ ]:
df.tail(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Applicant Income Group,Applicant Income
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y,Lower Middle Income,"(2877.5, 3812.5]"
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y,Upper Middle Income,"(3812.5, 5795.0]"
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y,High Income,"(5795.0, 81000.0]"
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y,High Income,"(5795.0, 81000.0]"
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N,Upper Middle Income,"(3812.5, 5795.0]"

In [ ]:
df['ApplicantIncome'].mean()

np.float64(5403.459283387622)

In [ ]:
df.isnull().sum()

Loan_ID                    0
Gender                    13
Married                    3
Dependents                15
Education                  0
Self_Employed             32
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                22
Loan_Amount_Term          14
Credit_History            50
Property_Area              0
Loan_Status                0
Applicant Income Group     0
Applicant Income           0
dtype: int64

In [ ]:
Existing features se new meaningful features banana aur categorical data ko ML-friendly numeric format me convert karna Feature Engineering kehlata hai.