                                    Pandas for Machine Learning Roadmap
    Module 1: Pandas Fundamentals

    Introduction to Pandas
    Series
    DataFrame
    Creating DataFrame
    Reading CSV, Excel, JSON
    Writing CSV, Excel

    Module 2: Data Exploration
    head()
    tail()
    sample()
    shape
    columns
    index
    info()
    describe()
    dtypes

    Module 3: Data Selection
    Column Selection
    Multiple Column Selection
    Row Selection
    loc[]
    iloc[]

Module 4: Data Filtering
Conditional Filtering
Multiple Conditions (&, |)
isin()
between()
query()

Module 5: Data Cleaning (Most Important for ML)

Missing Values
isnull()
notnull()
fillna()
dropna()
Duplicate Records
duplicated()
drop_duplicates()

Module 6: Data Transformation
Add New Columns
Update Existing Columns
Rename Columns
Change Data Types
astype()
replace()
apply()
map()

Module 7: String Operations
str.upper()
str.lower()
str.strip()
str.contains()
str.split()
str.replace()

Module 8: Date & Time Handling
to_datetime()
Year Extraction
Month Extraction
Day Extraction
Weekday Extraction
Date Difference
Module 9: Sorting & Ranking
sort_values()
sort_index()
rank()
nlargest()
nsmallest()

Module 10: Aggregation & Statistics
sum()
mean()
median()
mode()
max()
min()
count()
std()
var()
corr()
Module 11: GroupBy (Very Important)
groupby()
Single Aggregation
Multiple Aggregations
Custom Aggregations
GroupBy + Filter
Module 12: Reshaping Data
Pivot Table
Crosstab
Melt
Stack
Unstack
Module 13: Combining Data
concat()
merge()
Inner Join
Left Join
Right Join
Outer Join
join()

Module 14: Feature Engineering for ML
Creating Features
Binning (cut)
Quantile Binning (qcut)
Encoding Categories
Dummy Variables (get_dummies)
Label Encoding Preparation

In [ ]:
pip install pandas

In [ ]:
import pandas as pd
# How to Create Series
series=pd.Series([1,2,3,4,5])

In [ ]:
print(series)

In [ ]:
print(type(series))

In [3]:
# DataFrame
# How to Create DataFrame
import pandas as pd
data={'Name':['Alice','Bob','Charlie'],'Age':[25,30,35],'City':['New York','Los Angeles','Chicago']}
print(type(data))
df=pd.DataFrame(data)
print(type(df))

<class 'dict'>
<class 'pandas.core.frame.DataFrame'>

In [4]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [5]:
df=pd.read_csv('data.csv')
print(df)

     Roll    Name  Class  Marks
1  Vishnu     MCA    450    NaN
2   Vinit  B.Tech    487    NaN

In [7]:
dict={'Name':'Alice','Age':25,'City':'New York'}
df=pd.Series(dict)
print(df)

Name       Alice
Age           25
City    New York
dtype: object

In [8]:
print(type(df))

<class 'pandas.core.series.Series'>

In [12]:
data=pd.read_excel(r"C:\Users\Vishnu\Desktop\Python_Evening\RL_Task_Scheduling_Dataset.xlsx")

In [13]:
data

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0          1            91               9         3            28
1          2            12               9         3            55
2          3            56              12         4            16
3          4            83              14         4            59
4          5            57              12         1            79
..       ...           ...             ...       ...           ...
295      296            56              15         4            24
296      297            80               9         3            96
297      298            25               3         3            72
298      299            85               7         2            96
299      300            19               8         2            65

[300 rows x 5 columns]

In [15]:
data.head()

   Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0        1            91               9         3            28
1        2            12               9         3            55
2        3            56              12         4            16
3        4            83              14         4            59
4        5            57              12         1            79

In [16]:
data.tail()

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
295      296            56              15         4            24
296      297            80               9         3            96
297      298            25               3         3            72
298      299            85               7         2            96
299      300            19               8         2            65

In [17]:
data.head(20)

    Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0         1            91               9         3            28
1         2            12               9         3            55
2         3            56              12         4            16
3         4            83              14         4            59
4         5            57              12         1            79
5         6            20              10         5            17
6         7            61               7         2            67
7         8            26              13         5            58
8         9            66               7         4            42
9        10            62               7         2            87
10       11            55               8         4            73
11       12            93              14         1            52
12       13            82              15         3            73
13       14            56               9         1            56
14       15            98              10         3             3
15       16            23               8         3            75
16       17            90               6         1            35
17       18            68               7         4            48
18       19            27               9         1            95
19       20            35               9         1            47

In [30]:
print(data[10:21])

    Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
10       11            55               8         4            73
11       12            93              14         1            52
12       13            82              15         3            73
13       14            56               9         1            56
14       15            98              10         3             3
15       16            23               8         3            75
16       17            90               6         1            35
17       18            68               7         4            48
18       19            27               9         1            95
19       20            35               9         1            47
20       21            91               3         2            31

In [32]:
print(data.iloc[10:21,0:4])

    Task_ID  Task_Size_MB  Execution_Time  Priority
10       11            55               8         4
11       12            93              14         1
12       13            82              15         3
13       14            56               9         1
14       15            98              10         3
15       16            23               8         3
16       17            90               6         1
17       18            68               7         4
18       19            27               9         1
19       20            35               9         1
20       21            91               3         2

In [34]:
data.shape

(300, 5)

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Task_ID         300 non-null    int64
 1   Task_Size_MB    300 non-null    int64
 2   Execution_Time  300 non-null    int64
 3   Priority        300 non-null    int64
 4   Arrival_Time    300 non-null    int64
dtypes: int64(5)
memory usage: 11.8 KB

In [36]:
data.isnull().sum()

Task_ID           0
Task_Size_MB      0
Execution_Time    0
Priority          0
Arrival_Time      0
dtype: int64

In [37]:
data.columns

Index(['Task_ID', 'Task_Size_MB', 'Execution_Time', 'Priority',
       'Arrival_Time'],
      dtype='object')

In [39]:
data['Task_Size_MB'].value_counts()

Task_Size_MB
37    9
95    8
56    7
33    7
20    6
     ..
39    1
36    1
84    1
87    1
41    1
Name: count, Length: 87, dtype: int64

In [40]:
data['Task_Size_MB'].unique()

array([ 91,  12,  56,  83,  57,  20,  61,  26,  66,  62,  55,  93,  82,
        98,  23,  90,  68,  27,  35,  94,  65,  40,  10,  46,  29,  22,
        34,  72,  59,  74,  95,  52,  97,  42,  33,  53,  79,  71,  32,
        11,  51,  18,  43,  50,  60,  85,  15,  21,  37,  13,  17,  14,
        76,  88,  38,  81,  80,  70,  19,  24,  48,  99,  77,  54,  58,
        47,  92,  44,  16,  64,  63,  75,  39,  89,  78,  25, 100,  49,
        69,  31,  30,  36,  67,  96,  84,  87,  41])

In [42]:
data.index

RangeIndex(start=0, stop=300, step=1)

In [43]:
data.describe()

          Task_ID  Task_Size_MB  Execution_Time    Priority  Arrival_Time
count  300.000000    300.000000      300.000000  300.000000    300.000000
mean   150.500000     55.170000        8.116667    3.036667     52.006667
std     86.746758     27.261052        4.060132    1.417281     29.338640
min      1.000000     10.000000        1.000000    1.000000      1.000000
25%     75.750000     33.000000        5.000000    2.000000     27.000000
50%    150.500000     55.000000        8.000000    3.000000     53.000000
75%    225.250000     80.000000       11.250000    4.000000     77.000000
max    300.000000    100.000000       15.000000    5.000000    100.000000

In [44]:
data['Task_Size_MB'].mean()

np.float64(55.17)

In [45]:
data['Arrival_Time']

0      28
1      55
2      16
3      59
4      79
       ..
295    24
296    96
297    72
298    96
299    65
Name: Arrival_Time, Length: 300, dtype: int64

In [46]:
data[['Task_Size_MB','Arrival_Time']]

     Task_Size_MB  Arrival_Time
0              91            28
1              12            55
2              56            16
3              83            59
4              57            79
..            ...           ...
295            56            24
296            80            96
297            25            72
298            85            96
299            19            65

[300 rows x 2 columns]

In [47]:
data.loc[0]

Task_ID            1
Task_Size_MB      91
Execution_Time     9
Priority           3
Arrival_Time      28
Name: 0, dtype: int64

In [48]:
data.iloc[0]

Task_ID            1
Task_Size_MB      91
Execution_Time     9
Priority           3
Arrival_Time      28
Name: 0, dtype: int64

In [57]:
data.loc[0,'Arrival_Time']

np.int64(28)

In [58]:
data.iloc[0,4]

np.int64(28)

In [51]:
data

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0          1            91               9         3            28
1          2            12               9         3            55
2          3            56              12         4            16
3          4            83              14         4            59
4          5            57              12         1            79
..       ...           ...             ...       ...           ...
295      296            56              15         4            24
296      297            80               9         3            96
297      298            25               3         3            72
298      299            85               7         2            96
299      300            19               8         2            65

[300 rows x 5 columns]

In [60]:
data.sample(5)

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
69        70            33              12         1            74
287      288            44               5         3            93
185      186            44               8         5            70
290      291            25               7         3            14
91        92            81               6         4             2

In [61]:
data1=data.copy()

In [62]:
data1

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0          1            91               9         3            28
1          2            12               9         3            55
2          3            56              12         4            16
3          4            83              14         4            59
4          5            57              12         1            79
..       ...           ...             ...       ...           ...
295      296            56              15         4            24
296      297            80               9         3            96
297      298            25               3         3            72
298      299            85               7         2            96
299      300            19               8         2            65

[300 rows x 5 columns]

In [63]:
print(type(data1))

<class 'pandas.core.frame.DataFrame'>

In [64]:
print(data.loc[[295]])

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
295      296            56              15         4            24

In [ ]:
Module 4: Data Filtering
Conditional Filtering
Multiple Conditions (&, |)
isin()
between()
query()

In [65]:
data

     Task_ID  Task_Size_MB  Execution_Time  Priority  Arrival_Time
0          1            91               9         3            28
1          2            12               9         3            55
2          3            56              12         4            16
3          4            83              14         4            59
4          5            57              12         1            79
..       ...           ...             ...       ...           ...
295      296            56              15         4            24
296      297            80               9         3            96
297      298            25               3         3            72
298      299            85               7         2            96
299      300            19               8         2            65

[300 rows x 5 columns]

In [ ]:
Module 4: Data Filtering
Conditional Filtering
Multiple Conditions (&, |)
isin()
between()
query()

In [66]:
import pandas as pd

data=pd.DataFrame(

    {
        "Name":['Alice','Bob','Charlie','David','Eve'],
        "Age":[25,30,35,40,45],
        "City":['New York','Los Angeles','Chicago','Houston','Phoenix'],
        "Salary":[50000,60000,70000,80000,90000]

    }
)

In [67]:
data

      Name  Age         City  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000
4      Eve   45      Phoenix   90000

In [70]:
data[data['Age']>25]

      Name  Age         City  Salary
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000
4      Eve   45      Phoenix   90000

In [75]:
data[(data['Age']>25) | (data['Salary']>60000)]

      Name  Age         City  Salary
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000
4      Eve   45      Phoenix   90000

In [77]:
data[data['Age'].isin([30,40,50])]

    Name  Age         City  Salary
1    Bob   30  Los Angeles   60000
3  David   40      Houston   80000

In [78]:
data[data['Age'].between(30,40)]

      Name  Age         City  Salary
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000

In [80]:
data.query('Age > 35')

    Name  Age     City  Salary
3  David   40  Houston   80000
4    Eve   45  Phoenix   90000